// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: api/health/health.proto

package health

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HealthService_ListGroups_FullMethodName                = "/health.HealthService/ListGroups"
	HealthService_ListCriteria_FullMethodName              = "/health.HealthService/ListCriteria"
	HealthService_SetUserCriterion_FullMethodName          = "/health.HealthService/SetUserCriterion"
	HealthService_ResetCriteria_FullMethodName             = "/health.HealthService/ResetCriteria"
	HealthService_GetUserCriteria_FullMethodName           = "/health.HealthService/GetUserCriteria"
	HealthService_GetProgress_FullMethodName               = "/health.HealthService/GetProgress"
	HealthService_ImportCriteriaFromPdf_FullMethodName     = "/health.HealthService/ImportCriteriaFromPdf"
	HealthService_ConfirmPendingImport_FullMethodName      = "/health.HealthService/ConfirmPendingImport"
	HealthService_GetRecommendations_FullMethodName        = "/health.HealthService/GetRecommendations"
	HealthService_GetWeeklyRecommendations_FullMethodName  = "/health.HealthService/GetWeeklyRecommendations"
	HealthService_SendNotification_FullMethodName          = "/health.HealthService/SendNotification"
	HealthService_AdminListRecommendations_FullMethodName  = "/health.HealthService/AdminListRecommendations"
	HealthService_AdminUpsertRecommendation_FullMethodName = "/health.HealthService/AdminUpsertRecommendation"
	HealthService_AdminDeleteRecommendation_FullMethodName = "/health.HealthService/AdminDeleteRecommendation"
	HealthService_AdminUpsertCriterion_FullMethodName      = "/health.HealthService/AdminUpsertCriterion"
)

// HealthServiceClient is the client API for HealthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HealthServiceClient interface {
	// --- Criteria ---
	ListGroups(ctx context.Context, in *ListGroupsRequest, opts ...grpc.CallOption) (*ListGroupsResponse, error)
	ListCriteria(ctx context.Context, in *ListCriteriaRequest, opts ...grpc.CallOption) (*ListCriteriaResponse, error)
	SetUserCriterion(ctx context.Context, in *SetUserCriterionRequest, opts ...grpc.CallOption) (*SetUserCriterionResponse, error)
	ResetCriteria(ctx context.Context, in *ResetCriteriaRequest, opts ...grpc.CallOption) (*ResetCriteriaResponse, error)
	GetUserCriteria(ctx context.Context, in *GetUserCriteriaRequest, opts ...grpc.CallOption) (*GetUserCriteriaResponse, error)
	GetProgress(ctx context.Context, in *GetProgressRequest, opts ...grpc.CallOption) (*GetProgressResponse, error)
	// Client streams 1+ PDFs (or same stream protocol): extracts text, calls OpenAI via creteria_parser, returns suggestions + pending_import_id (Redis, 1h) until the user confirms.
	ImportCriteriaFromPdf(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ImportCriteriaFromPdfRequest, ImportCriteriaFromPdfResponse], error)
	// Apply or discard a pending import produced by ImportCriteriaFromPdf. accept=false removes Redis only.
	ConfirmPendingImport(ctx context.Context, in *ConfirmPendingImportRequest, opts ...grpc.CallOption) (*ConfirmPendingImportResponse, error)
	// --- Recommendations ---
	GetRecommendations(ctx context.Context, in *GetRecommendationsRequest, opts ...grpc.CallOption) (*GetRecommendationsResponse, error)
	GetWeeklyRecommendations(ctx context.Context, in *GetWeeklyRecommendationsRequest, opts ...grpc.CallOption) (*GetWeeklyRecommendationsResponse, error)
	// --- Notifications ---
	SendNotification(ctx context.Context, in *SendNotificationRequest, opts ...grpc.CallOption) (*SendNotificationResponse, error)
	// --- Admin ---
	AdminListRecommendations(ctx context.Context, in *AdminListRecommendationsRequest, opts ...grpc.CallOption) (*AdminListRecommendationsResponse, error)
	AdminUpsertRecommendation(ctx context.Context, in *AdminUpsertRecommendationRequest, opts ...grpc.CallOption) (*AdminUpsertRecommendationResponse, error)
	AdminDeleteRecommendation(ctx context.Context, in *AdminDeleteRecommendationRequest, opts ...grpc.CallOption) (*AdminDeleteRecommendationResponse, error)
	AdminUpsertCriterion(ctx context.Context, in *AdminUpsertCriterionRequest, opts ...grpc.CallOption) (*AdminUpsertCriterionResponse, error)
}

type healthServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHealthServiceClient(cc grpc.ClientConnInterface) HealthServiceClient {
	return &healthServiceClient{cc}
}

func (c *healthServiceClient) ListGroups(ctx context.Context, in *ListGroupsRequest, opts ...grpc.CallOption) (*ListGroupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGroupsResponse)
	err := c.cc.Invoke(ctx, HealthService_ListGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthServiceClient) ListCriteria(ctx context.Context, in *ListCriteriaRequest, opts ...grpc.CallOption) (*ListCriteriaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCriteriaResponse)
	err := c.cc.Invoke(ctx, HealthService_ListCriteria_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthServiceClient) SetUserCriterion(ctx context.Context, in *SetUserCriterionRequest, opts ...grpc.CallOption) (*SetUserCriterionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetUserCriterionResponse)
	err := c.cc.Invoke(ctx, HealthService_SetUserCriterion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthServiceClient) ResetCriteria(ctx context.Context, in *ResetCriteriaRequest, opts ...grpc.CallOption) (*ResetCriteriaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetCriteriaResponse)
	err := c.cc.Invoke(ctx, HealthService_ResetCriteria_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthServiceClient) GetUserCriteria(ctx context.Context, in *GetUserCriteriaRequest, opts ...grpc.CallOption) (*GetUserCriteriaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserCriteriaResponse)
	err := c.cc.Invoke(ctx, HealthService_GetUserCriteria_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthServiceClient) GetProgress(ctx context.Context, in *GetProgressRequest, opts ...grpc.CallOption) (*GetProgressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProgressResponse)
	err := c.cc.Invoke(ctx, HealthService_GetProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthServiceClient) ImportCriteriaFromPdf(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ImportCriteriaFromPdfRequest, ImportCriteriaFromPdfResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HealthService_ServiceDesc.Streams[0], HealthService_ImportCriteriaFromPdf_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ImportCriteriaFromPdfRequest, ImportCriteriaFromPdfResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HealthService_ImportCriteriaFromPdfClient = grpc.ClientStreamingClient[ImportCriteriaFromPdfRequest, ImportCriteriaFromPdfResponse]

func (c *healthServiceClient) ConfirmPendingImport(ctx context.Context, in *ConfirmPendingImportRequest, opts ...grpc.CallOption) (*ConfirmPendingImportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmPendingImportResponse)
	err := c.cc.Invoke(ctx, HealthService_ConfirmPendingImport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthServiceClient) GetRecommendations(ctx context.Context, in *GetRecommendationsRequest, opts ...grpc.CallOption) (*GetRecommendationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRecommendationsResponse)
	err := c.cc.Invoke(ctx, HealthService_GetRecommendations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthServiceClient) GetWeeklyRecommendations(ctx context.Context, in *GetWeeklyRecommendationsRequest, opts ...grpc.CallOption) (*GetWeeklyRecommendationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWeeklyRecommendationsResponse)
	err := c.cc.Invoke(ctx, HealthService_GetWeeklyRecommendations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthServiceClient) SendNotification(ctx context.Context, in *SendNotificationRequest, opts ...grpc.CallOption) (*SendNotificationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendNotificationResponse)
	err := c.cc.Invoke(ctx, HealthService_SendNotification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthServiceClient) AdminListRecommendations(ctx context.Context, in *AdminListRecommendationsRequest, opts ...grpc.CallOption) (*AdminListRecommendationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminListRecommendationsResponse)
	err := c.cc.Invoke(ctx, HealthService_AdminListRecommendations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthServiceClient) AdminUpsertRecommendation(ctx context.Context, in *AdminUpsertRecommendationRequest, opts ...grpc.CallOption) (*AdminUpsertRecommendationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminUpsertRecommendationResponse)
	err := c.cc.Invoke(ctx, HealthService_AdminUpsertRecommendation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthServiceClient) AdminDeleteRecommendation(ctx context.Context, in *AdminDeleteRecommendationRequest, opts ...grpc.CallOption) (*AdminDeleteRecommendationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminDeleteRecommendationResponse)
	err := c.cc.Invoke(ctx, HealthService_AdminDeleteRecommendation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthServiceClient) AdminUpsertCriterion(ctx context.Context, in *AdminUpsertCriterionRequest, opts ...grpc.CallOption) (*AdminUpsertCriterionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminUpsertCriterionResponse)
	err := c.cc.Invoke(ctx, HealthService_AdminUpsertCriterion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HealthServiceServer is the server API for HealthService service.
// All implementations must embed UnimplementedHealthServiceServer
// for forward compatibility.
type HealthServiceServer interface {
	// --- Criteria ---
	ListGroups(context.Context, *ListGroupsRequest) (*ListGroupsResponse, error)
	ListCriteria(context.Context, *ListCriteriaRequest) (*ListCriteriaResponse, error)
	SetUserCriterion(context.Context, *SetUserCriterionRequest) (*SetUserCriterionResponse, error)
	ResetCriteria(context.Context, *ResetCriteriaRequest) (*ResetCriteriaResponse, error)
	GetUserCriteria(context.Context, *GetUserCriteriaRequest) (*GetUserCriteriaResponse, error)
	GetProgress(context.Context, *GetProgressRequest) (*GetProgressResponse, error)
	// Client streams 1+ PDFs (or same stream protocol): extracts text, calls OpenAI via creteria_parser, returns suggestions + pending_import_id (Redis, 1h) until the user confirms.
	ImportCriteriaFromPdf(grpc.ClientStreamingServer[ImportCriteriaFromPdfRequest, ImportCriteriaFromPdfResponse]) error
	// Apply or discard a pending import produced by ImportCriteriaFromPdf. accept=false removes Redis only.
	ConfirmPendingImport(context.Context, *ConfirmPendingImportRequest) (*ConfirmPendingImportResponse, error)
	// --- Recommendations ---
	GetRecommendations(context.Context, *GetRecommendationsRequest) (*GetRecommendationsResponse, error)
	GetWeeklyRecommendations(context.Context, *GetWeeklyRecommendationsRequest) (*GetWeeklyRecommendationsResponse, error)
	// --- Notifications ---
	SendNotification(context.Context, *SendNotificationRequest) (*SendNotificationResponse, error)
	// --- Admin ---
	AdminListRecommendations(context.Context, *AdminListRecommendationsRequest) (*AdminListRecommendationsResponse, error)
	AdminUpsertRecommendation(context.Context, *AdminUpsertRecommendationRequest) (*AdminUpsertRecommendationResponse, error)
	AdminDeleteRecommendation(context.Context, *AdminDeleteRecommendationRequest) (*AdminDeleteRecommendationResponse, error)
	AdminUpsertCriterion(context.Context, *AdminUpsertCriterionRequest) (*AdminUpsertCriterionResponse, error)
	mustEmbedUnimplementedHealthServiceServer()
}

// UnimplementedHealthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHealthServiceServer struct{}

func (UnimplementedHealthServiceServer) ListGroups(context.Context, *ListGroupsRequest) (*ListGroupsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListGroups not implemented")
}
func (UnimplementedHealthServiceServer) ListCriteria(context.Context, *ListCriteriaRequest) (*ListCriteriaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCriteria not implemented")
}
func (UnimplementedHealthServiceServer) SetUserCriterion(context.Context, *SetUserCriterionRequest) (*SetUserCriterionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetUserCriterion not implemented")
}
func (UnimplementedHealthServiceServer) ResetCriteria(context.Context, *ResetCriteriaRequest) (*ResetCriteriaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResetCriteria not implemented")
}
func (UnimplementedHealthServiceServer) GetUserCriteria(context.Context, *GetUserCriteriaRequest) (*GetUserCriteriaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserCriteria not implemented")
}
func (UnimplementedHealthServiceServer) GetProgress(context.Context, *GetProgressRequest) (*GetProgressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProgress not implemented")
}
func (UnimplementedHealthServiceServer) ImportCriteriaFromPdf(grpc.ClientStreamingServer[ImportCriteriaFromPdfRequest, ImportCriteriaFromPdfResponse]) error {
	return status.Error(codes.Unimplemented, "method ImportCriteriaFromPdf not implemented")
}
func (UnimplementedHealthServiceServer) ConfirmPendingImport(context.Context, *ConfirmPendingImportRequest) (*ConfirmPendingImportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmPendingImport not implemented")
}
func (UnimplementedHealthServiceServer) GetRecommendations(context.Context, *GetRecommendationsRequest) (*GetRecommendationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRecommendations not implemented")
}
func (UnimplementedHealthServiceServer) GetWeeklyRecommendations(context.Context, *GetWeeklyRecommendationsRequest) (*GetWeeklyRecommendationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWeeklyRecommendations not implemented")
}
func (UnimplementedHealthServiceServer) SendNotification(context.Context, *SendNotificationRequest) (*SendNotificationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendNotification not implemented")
}
func (UnimplementedHealthServiceServer) AdminListRecommendations(context.Context, *AdminListRecommendationsRequest) (*AdminListRecommendationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminListRecommendations not implemented")
}
func (UnimplementedHealthServiceServer) AdminUpsertRecommendation(context.Context, *AdminUpsertRecommendationRequest) (*AdminUpsertRecommendationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminUpsertRecommendation not implemented")
}
func (UnimplementedHealthServiceServer) AdminDeleteRecommendation(context.Context, *AdminDeleteRecommendationRequest) (*AdminDeleteRecommendationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminDeleteRecommendation not implemented")
}
func (UnimplementedHealthServiceServer) AdminUpsertCriterion(context.Context, *AdminUpsertCriterionRequest) (*AdminUpsertCriterionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdminUpsertCriterion not implemented")
}
func (UnimplementedHealthServiceServer) mustEmbedUnimplementedHealthServiceServer() {}
func (UnimplementedHealthServiceServer) testEmbeddedByValue()                       {}

// UnsafeHealthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HealthServiceServer will
// result in compilation errors.
type UnsafeHealthServiceServer interface {
	mustEmbedUnimplementedHealthServiceServer()
}

func RegisterHealthServiceServer(s grpc.ServiceRegistrar, srv HealthServiceServer) {
	// If the following call panics, it indicates UnimplementedHealthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HealthService_ServiceDesc, srv)
}

func _HealthService_ListGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServiceServer).ListGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthService_ListGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServiceServer).ListGroups(ctx, req.(*ListGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HealthService_ListCriteria_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCriteriaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServiceServer).ListCriteria(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthService_ListCriteria_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServiceServer).ListCriteria(ctx, req.(*ListCriteriaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HealthService_SetUserCriterion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUserCriterionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServiceServer).SetUserCriterion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthService_SetUserCriterion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServiceServer).SetUserCriterion(ctx, req.(*SetUserCriterionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HealthService_ResetCriteria_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetCriteriaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServiceServer).ResetCriteria(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthService_ResetCriteria_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServiceServer).ResetCriteria(ctx, req.(*ResetCriteriaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HealthService_GetUserCriteria_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserCriteriaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServiceServer).GetUserCriteria(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthService_GetUserCriteria_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServiceServer).GetUserCriteria(ctx, req.(*GetUserCriteriaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HealthService_GetProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServiceServer).GetProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthService_GetProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServiceServer).GetProgress(ctx, req.(*GetProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HealthService_ImportCriteriaFromPdf_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HealthServiceServer).ImportCriteriaFromPdf(&grpc.GenericServerStream[ImportCriteriaFromPdfRequest, ImportCriteriaFromPdfResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HealthService_ImportCriteriaFromPdfServer = grpc.ClientStreamingServer[ImportCriteriaFromPdfRequest, ImportCriteriaFromPdfResponse]

func _HealthService_ConfirmPendingImport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmPendingImportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServiceServer).ConfirmPendingImport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthService_ConfirmPendingImport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServiceServer).ConfirmPendingImport(ctx, req.(*ConfirmPendingImportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HealthService_GetRecommendations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecommendationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServiceServer).GetRecommendations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthService_GetRecommendations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServiceServer).GetRecommendations(ctx, req.(*GetRecommendationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HealthService_GetWeeklyRecommendations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWeeklyRecommendationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServiceServer).GetWeeklyRecommendations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthService_GetWeeklyRecommendations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServiceServer).GetWeeklyRecommendations(ctx, req.(*GetWeeklyRecommendationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HealthService_SendNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServiceServer).SendNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthService_SendNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServiceServer).SendNotification(ctx, req.(*SendNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HealthService_AdminListRecommendations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminListRecommendationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServiceServer).AdminListRecommendations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthService_AdminListRecommendations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServiceServer).AdminListRecommendations(ctx, req.(*AdminListRecommendationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HealthService_AdminUpsertRecommendation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminUpsertRecommendationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServiceServer).AdminUpsertRecommendation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthService_AdminUpsertRecommendation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServiceServer).AdminUpsertRecommendation(ctx, req.(*AdminUpsertRecommendationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HealthService_AdminDeleteRecommendation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminDeleteRecommendationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServiceServer).AdminDeleteRecommendation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthService_AdminDeleteRecommendation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServiceServer).AdminDeleteRecommendation(ctx, req.(*AdminDeleteRecommendationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HealthService_AdminUpsertCriterion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminUpsertCriterionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServiceServer).AdminUpsertCriterion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthService_AdminUpsertCriterion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServiceServer).AdminUpsertCriterion(ctx, req.(*AdminUpsertCriterionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HealthService_ServiceDesc is the grpc.ServiceDesc for HealthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HealthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "health.HealthService",
	HandlerType: (*HealthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListGroups",
			Handler:    _HealthService_ListGroups_Handler,
		},
		{
			MethodName: "ListCriteria",
			Handler:    _HealthService_ListCriteria_Handler,
		},
		{
			MethodName: "SetUserCriterion",
			Handler:    _HealthService_SetUserCriterion_Handler,
		},
		{
			MethodName: "ResetCriteria",
			Handler:    _HealthService_ResetCriteria_Handler,
		},
		{
			MethodName: "GetUserCriteria",
			Handler:    _HealthService_GetUserCriteria_Handler,
		},
		{
			MethodName: "GetProgress",
			Handler:    _HealthService_GetProgress_Handler,
		},
		{
			MethodName: "ConfirmPendingImport",
			Handler:    _HealthService_ConfirmPendingImport_Handler,
		},
		{
			MethodName: "GetRecommendations",
			Handler:    _HealthService_GetRecommendations_Handler,
		},
		{
			MethodName: "GetWeeklyRecommendations",
			Handler:    _HealthService_GetWeeklyRecommendations_Handler,
		},
		{
			MethodName: "SendNotification",
			Handler:    _HealthService_SendNotification_Handler,
		},
		{
			MethodName: "AdminListRecommendations",
			Handler:    _HealthService_AdminListRecommendations_Handler,
		},
		{
			MethodName: "AdminUpsertRecommendation",
			Handler:    _HealthService_AdminUpsertRecommendation_Handler,
		},
		{
			MethodName: "AdminDeleteRecommendation",
			Handler:    _HealthService_AdminDeleteRecommendation_Handler,
		},
		{
			MethodName: "AdminUpsertCriterion",
			Handler:    _HealthService_AdminUpsertCriterion_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ImportCriteriaFromPdf",
			Handler:       _HealthService_ImportCriteriaFromPdf_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "api/health/health.proto",
}
