// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: health.proto

package health

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListCriteriaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCriteriaRequest) Reset() {
	*x = ListCriteriaRequest{}
	mi := &file_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCriteriaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCriteriaRequest) ProtoMessage() {}

func (x *ListCriteriaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCriteriaRequest.ProtoReflect.Descriptor instead.
func (*ListCriteriaRequest) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{0}
}

type Criterion struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Id                     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code                   string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name                   string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description            string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ValueType              string                 `protobuf:"bytes,5,opt,name=value_type,json=valueType,proto3" json:"value_type,omitempty"`
	Unit                   string                 `protobuf:"bytes,6,opt,name=unit,proto3" json:"unit,omitempty"`
	InputModes             []string               `protobuf:"bytes,7,rep,name=input_modes,json=inputModes,proto3" json:"input_modes,omitempty"`
	RecurrenceIntervalDays int32                  `protobuf:"varint,8,opt,name=recurrence_interval_days,json=recurrenceIntervalDays,proto3" json:"recurrence_interval_days,omitempty"`
	IsActive               bool                   `protobuf:"varint,9,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Criterion) Reset() {
	*x = Criterion{}
	mi := &file_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Criterion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Criterion) ProtoMessage() {}

func (x *Criterion) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Criterion.ProtoReflect.Descriptor instead.
func (*Criterion) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{1}
}

func (x *Criterion) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Criterion) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Criterion) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Criterion) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Criterion) GetValueType() string {
	if x != nil {
		return x.ValueType
	}
	return ""
}

func (x *Criterion) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *Criterion) GetInputModes() []string {
	if x != nil {
		return x.InputModes
	}
	return nil
}

func (x *Criterion) GetRecurrenceIntervalDays() int32 {
	if x != nil {
		return x.RecurrenceIntervalDays
	}
	return 0
}

func (x *Criterion) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type ListCriteriaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Criteria      []*Criterion           `protobuf:"bytes,1,rep,name=criteria,proto3" json:"criteria,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCriteriaResponse) Reset() {
	*x = ListCriteriaResponse{}
	mi := &file_health_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCriteriaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCriteriaResponse) ProtoMessage() {}

func (x *ListCriteriaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCriteriaResponse.ProtoReflect.Descriptor instead.
func (*ListCriteriaResponse) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{2}
}

func (x *ListCriteriaResponse) GetCriteria() []*Criterion {
	if x != nil {
		return x.Criteria
	}
	return nil
}

type ListLabTestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLabTestsRequest) Reset() {
	*x = ListLabTestsRequest{}
	mi := &file_health_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLabTestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLabTestsRequest) ProtoMessage() {}

func (x *ListLabTestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLabTestsRequest.ProtoReflect.Descriptor instead.
func (*ListLabTestsRequest) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{3}
}

type LabTest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	CriterionIds  []string               `protobuf:"bytes,5,rep,name=criterion_ids,json=criterionIds,proto3" json:"criterion_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabTest) Reset() {
	*x = LabTest{}
	mi := &file_health_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabTest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabTest) ProtoMessage() {}

func (x *LabTest) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabTest.ProtoReflect.Descriptor instead.
func (*LabTest) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{4}
}

func (x *LabTest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LabTest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *LabTest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LabTest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *LabTest) GetCriterionIds() []string {
	if x != nil {
		return x.CriterionIds
	}
	return nil
}

type ListLabTestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LabTests      []*LabTest             `protobuf:"bytes,1,rep,name=lab_tests,json=labTests,proto3" json:"lab_tests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLabTestsResponse) Reset() {
	*x = ListLabTestsResponse{}
	mi := &file_health_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLabTestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLabTestsResponse) ProtoMessage() {}

func (x *ListLabTestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLabTestsResponse.ProtoReflect.Descriptor instead.
func (*ListLabTestsResponse) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{5}
}

func (x *ListLabTestsResponse) GetLabTests() []*LabTest {
	if x != nil {
		return x.LabTests
	}
	return nil
}

type CreateNumericEventRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	HealthCriterionId string                 `protobuf:"bytes,2,opt,name=health_criterion_id,json=healthCriterionId,proto3" json:"health_criterion_id,omitempty"`
	LabTestId         string                 `protobuf:"bytes,3,opt,name=lab_test_id,json=labTestId,proto3" json:"lab_test_id,omitempty"`
	NumericValue      float64                `protobuf:"fixed64,4,opt,name=numeric_value,json=numericValue,proto3" json:"numeric_value,omitempty"`
	OccurredAt        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Source            string                 `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	Note              string                 `protobuf:"bytes,7,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateNumericEventRequest) Reset() {
	*x = CreateNumericEventRequest{}
	mi := &file_health_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNumericEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNumericEventRequest) ProtoMessage() {}

func (x *CreateNumericEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNumericEventRequest.ProtoReflect.Descriptor instead.
func (*CreateNumericEventRequest) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{6}
}

func (x *CreateNumericEventRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateNumericEventRequest) GetHealthCriterionId() string {
	if x != nil {
		return x.HealthCriterionId
	}
	return ""
}

func (x *CreateNumericEventRequest) GetLabTestId() string {
	if x != nil {
		return x.LabTestId
	}
	return ""
}

func (x *CreateNumericEventRequest) GetNumericValue() float64 {
	if x != nil {
		return x.NumericValue
	}
	return 0
}

func (x *CreateNumericEventRequest) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *CreateNumericEventRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *CreateNumericEventRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type CreateBooleanEventRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	HealthCriterionId string                 `protobuf:"bytes,2,opt,name=health_criterion_id,json=healthCriterionId,proto3" json:"health_criterion_id,omitempty"`
	BooleanValue      string                 `protobuf:"bytes,3,opt,name=boolean_value,json=booleanValue,proto3" json:"boolean_value,omitempty"`
	OccurredAt        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Source            string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	Note              string                 `protobuf:"bytes,6,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateBooleanEventRequest) Reset() {
	*x = CreateBooleanEventRequest{}
	mi := &file_health_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBooleanEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBooleanEventRequest) ProtoMessage() {}

func (x *CreateBooleanEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBooleanEventRequest.ProtoReflect.Descriptor instead.
func (*CreateBooleanEventRequest) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{7}
}

func (x *CreateBooleanEventRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateBooleanEventRequest) GetHealthCriterionId() string {
	if x != nil {
		return x.HealthCriterionId
	}
	return ""
}

func (x *CreateBooleanEventRequest) GetBooleanValue() string {
	if x != nil {
		return x.BooleanValue
	}
	return ""
}

func (x *CreateBooleanEventRequest) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *CreateBooleanEventRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *CreateBooleanEventRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type CreateMarkDoneEventRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	HealthCriterionId string                 `protobuf:"bytes,2,opt,name=health_criterion_id,json=healthCriterionId,proto3" json:"health_criterion_id,omitempty"`
	OccurredAt        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Source            string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Note              string                 `protobuf:"bytes,5,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateMarkDoneEventRequest) Reset() {
	*x = CreateMarkDoneEventRequest{}
	mi := &file_health_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMarkDoneEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMarkDoneEventRequest) ProtoMessage() {}

func (x *CreateMarkDoneEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMarkDoneEventRequest.ProtoReflect.Descriptor instead.
func (*CreateMarkDoneEventRequest) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{8}
}

func (x *CreateMarkDoneEventRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateMarkDoneEventRequest) GetHealthCriterionId() string {
	if x != nil {
		return x.HealthCriterionId
	}
	return ""
}

func (x *CreateMarkDoneEventRequest) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *CreateMarkDoneEventRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *CreateMarkDoneEventRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type EventResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId            string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	HealthCriterionId string                 `protobuf:"bytes,3,opt,name=health_criterion_id,json=healthCriterionId,proto3" json:"health_criterion_id,omitempty"`
	EventType         string                 `protobuf:"bytes,4,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	OccurredAt        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	RecordedAt        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=recorded_at,json=recordedAt,proto3" json:"recorded_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EventResponse) Reset() {
	*x = EventResponse{}
	mi := &file_health_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventResponse) ProtoMessage() {}

func (x *EventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventResponse.ProtoReflect.Descriptor instead.
func (*EventResponse) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{9}
}

func (x *EventResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EventResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EventResponse) GetHealthCriterionId() string {
	if x != nil {
		return x.HealthCriterionId
	}
	return ""
}

func (x *EventResponse) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *EventResponse) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *EventResponse) GetRecordedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RecordedAt
	}
	return nil
}

type CreateDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StorageKey    string                 `protobuf:"bytes,2,opt,name=storage_key,json=storageKey,proto3" json:"storage_key,omitempty"`
	MimeType      string                 `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	ByteSize      int64                  `protobuf:"varint,4,opt,name=byte_size,json=byteSize,proto3" json:"byte_size,omitempty"`
	Sha256        string                 `protobuf:"bytes,5,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDocumentRequest) Reset() {
	*x = CreateDocumentRequest{}
	mi := &file_health_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDocumentRequest) ProtoMessage() {}

func (x *CreateDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDocumentRequest.ProtoReflect.Descriptor instead.
func (*CreateDocumentRequest) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{10}
}

func (x *CreateDocumentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateDocumentRequest) GetStorageKey() string {
	if x != nil {
		return x.StorageKey
	}
	return ""
}

func (x *CreateDocumentRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *CreateDocumentRequest) GetByteSize() int64 {
	if x != nil {
		return x.ByteSize
	}
	return 0
}

func (x *CreateDocumentRequest) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type DocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StorageKey    string                 `protobuf:"bytes,3,opt,name=storage_key,json=storageKey,proto3" json:"storage_key,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentResponse) Reset() {
	*x = DocumentResponse{}
	mi := &file_health_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentResponse) ProtoMessage() {}

func (x *DocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentResponse.ProtoReflect.Descriptor instead.
func (*DocumentResponse) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{11}
}

func (x *DocumentResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DocumentResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DocumentResponse) GetStorageKey() string {
	if x != nil {
		return x.StorageKey
	}
	return ""
}

func (x *DocumentResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetDashboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDashboardRequest) Reset() {
	*x = GetDashboardRequest{}
	mi := &file_health_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDashboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDashboardRequest) ProtoMessage() {}

func (x *GetDashboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDashboardRequest.ProtoReflect.Descriptor instead.
func (*GetDashboardRequest) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{12}
}

func (x *GetDashboardRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DashboardResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Level           string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	ProgressPercent float64                `protobuf:"fixed64,2,opt,name=progress_percent,json=progressPercent,proto3" json:"progress_percent,omitempty"`
	TotalCriteria   int32                  `protobuf:"varint,3,opt,name=total_criteria,json=totalCriteria,proto3" json:"total_criteria,omitempty"`
	FilledCriteria  int32                  `protobuf:"varint,4,opt,name=filled_criteria,json=filledCriteria,proto3" json:"filled_criteria,omitempty"`
	OverdueCriteria int32                  `protobuf:"varint,5,opt,name=overdue_criteria,json=overdueCriteria,proto3" json:"overdue_criteria,omitempty"`
	States          []*CriterionState      `protobuf:"bytes,6,rep,name=states,proto3" json:"states,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DashboardResponse) Reset() {
	*x = DashboardResponse{}
	mi := &file_health_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardResponse) ProtoMessage() {}

func (x *DashboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardResponse.ProtoReflect.Descriptor instead.
func (*DashboardResponse) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{13}
}

func (x *DashboardResponse) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *DashboardResponse) GetProgressPercent() float64 {
	if x != nil {
		return x.ProgressPercent
	}
	return 0
}

func (x *DashboardResponse) GetTotalCriteria() int32 {
	if x != nil {
		return x.TotalCriteria
	}
	return 0
}

func (x *DashboardResponse) GetFilledCriteria() int32 {
	if x != nil {
		return x.FilledCriteria
	}
	return 0
}

func (x *DashboardResponse) GetOverdueCriteria() int32 {
	if x != nil {
		return x.OverdueCriteria
	}
	return 0
}

func (x *DashboardResponse) GetStates() []*CriterionState {
	if x != nil {
		return x.States
	}
	return nil
}

type CriterionState struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CriterionId      string                 `protobuf:"bytes,1,opt,name=criterion_id,json=criterionId,proto3" json:"criterion_id,omitempty"`
	CriterionName    string                 `protobuf:"bytes,2,opt,name=criterion_name,json=criterionName,proto3" json:"criterion_name,omitempty"`
	Status           string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	LastEventAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_event_at,json=lastEventAt,proto3" json:"last_event_at,omitempty"`
	LastValueSummary string                 `protobuf:"bytes,5,opt,name=last_value_summary,json=lastValueSummary,proto3" json:"last_value_summary,omitempty"`
	Recommendation   string                 `protobuf:"bytes,6,opt,name=recommendation,proto3" json:"recommendation,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CriterionState) Reset() {
	*x = CriterionState{}
	mi := &file_health_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CriterionState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CriterionState) ProtoMessage() {}

func (x *CriterionState) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CriterionState.ProtoReflect.Descriptor instead.
func (*CriterionState) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{14}
}

func (x *CriterionState) GetCriterionId() string {
	if x != nil {
		return x.CriterionId
	}
	return ""
}

func (x *CriterionState) GetCriterionName() string {
	if x != nil {
		return x.CriterionName
	}
	return ""
}

func (x *CriterionState) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CriterionState) GetLastEventAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastEventAt
	}
	return nil
}

func (x *CriterionState) GetLastValueSummary() string {
	if x != nil {
		return x.LastValueSummary
	}
	return ""
}

func (x *CriterionState) GetRecommendation() string {
	if x != nil {
		return x.Recommendation
	}
	return ""
}

type GetUserCriterionStatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserCriterionStatesRequest) Reset() {
	*x = GetUserCriterionStatesRequest{}
	mi := &file_health_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserCriterionStatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserCriterionStatesRequest) ProtoMessage() {}

func (x *GetUserCriterionStatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserCriterionStatesRequest.ProtoReflect.Descriptor instead.
func (*GetUserCriterionStatesRequest) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{15}
}

func (x *GetUserCriterionStatesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserCriterionStatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	States        []*CriterionState      `protobuf:"bytes,1,rep,name=states,proto3" json:"states,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserCriterionStatesResponse) Reset() {
	*x = GetUserCriterionStatesResponse{}
	mi := &file_health_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserCriterionStatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserCriterionStatesResponse) ProtoMessage() {}

func (x *GetUserCriterionStatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserCriterionStatesResponse.ProtoReflect.Descriptor instead.
func (*GetUserCriterionStatesResponse) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{16}
}

func (x *GetUserCriterionStatesResponse) GetStates() []*CriterionState {
	if x != nil {
		return x.States
	}
	return nil
}

type SendNotificationRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Channel          string                 `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	NotificationType string                 `protobuf:"bytes,3,opt,name=notification_type,json=notificationType,proto3" json:"notification_type,omitempty"`
	TemplateCode     string                 `protobuf:"bytes,4,opt,name=template_code,json=templateCode,proto3" json:"template_code,omitempty"`
	PayloadJson      string                 `protobuf:"bytes,5,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SendNotificationRequest) Reset() {
	*x = SendNotificationRequest{}
	mi := &file_health_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationRequest) ProtoMessage() {}

func (x *SendNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationRequest.ProtoReflect.Descriptor instead.
func (*SendNotificationRequest) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{17}
}

func (x *SendNotificationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SendNotificationRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *SendNotificationRequest) GetNotificationType() string {
	if x != nil {
		return x.NotificationType
	}
	return ""
}

func (x *SendNotificationRequest) GetTemplateCode() string {
	if x != nil {
		return x.TemplateCode
	}
	return ""
}

func (x *SendNotificationRequest) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

type SendNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNotificationResponse) Reset() {
	*x = SendNotificationResponse{}
	mi := &file_health_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationResponse) ProtoMessage() {}

func (x *SendNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationResponse.ProtoReflect.Descriptor instead.
func (*SendNotificationResponse) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{18}
}

var File_health_proto protoreflect.FileDescriptor

const file_health_proto_rawDesc = "" +
	"\n" +
	"\fhealth.proto\x12\x06health\x1a\x1fgoogle/protobuf/timestamp.proto\"\x15\n" +
	"\x13ListCriteriaRequest\"\x90\x02\n" +
	"\tCriterion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"value_type\x18\x05 \x01(\tR\tvalueType\x12\x12\n" +
	"\x04unit\x18\x06 \x01(\tR\x04unit\x12\x1f\n" +
	"\vinput_modes\x18\a \x03(\tR\n" +
	"inputModes\x128\n" +
	"\x18recurrence_interval_days\x18\b \x01(\x05R\x16recurrenceIntervalDays\x12\x1b\n" +
	"\tis_active\x18\t \x01(\bR\bisActive\"E\n" +
	"\x14ListCriteriaResponse\x12-\n" +
	"\bcriteria\x18\x01 \x03(\v2\x11.health.CriterionR\bcriteria\"\x15\n" +
	"\x13ListLabTestsRequest\"\x88\x01\n" +
	"\aLabTest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12#\n" +
	"\rcriterion_ids\x18\x05 \x03(\tR\fcriterionIds\"D\n" +
	"\x14ListLabTestsResponse\x12,\n" +
	"\tlab_tests\x18\x01 \x03(\v2\x0f.health.LabTestR\blabTests\"\x92\x02\n" +
	"\x19CreateNumericEventRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12.\n" +
	"\x13health_criterion_id\x18\x02 \x01(\tR\x11healthCriterionId\x12\x1e\n" +
	"\vlab_test_id\x18\x03 \x01(\tR\tlabTestId\x12#\n" +
	"\rnumeric_value\x18\x04 \x01(\x01R\fnumericValue\x12;\n" +
	"\voccurred_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\x12\x12\n" +
	"\x04note\x18\a \x01(\tR\x04note\"\xf2\x01\n" +
	"\x19CreateBooleanEventRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12.\n" +
	"\x13health_criterion_id\x18\x02 \x01(\tR\x11healthCriterionId\x12#\n" +
	"\rboolean_value\x18\x03 \x01(\tR\fbooleanValue\x12;\n" +
	"\voccurred_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12\x12\n" +
	"\x04note\x18\x06 \x01(\tR\x04note\"\xce\x01\n" +
	"\x1aCreateMarkDoneEventRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12.\n" +
	"\x13health_criterion_id\x18\x02 \x01(\tR\x11healthCriterionId\x12;\n" +
	"\voccurred_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x12\n" +
	"\x04note\x18\x05 \x01(\tR\x04note\"\x81\x02\n" +
	"\rEventResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12.\n" +
	"\x13health_criterion_id\x18\x03 \x01(\tR\x11healthCriterionId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x04 \x01(\tR\teventType\x12;\n" +
	"\voccurred_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12;\n" +
	"\vrecorded_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"recordedAt\"\xa3\x01\n" +
	"\x15CreateDocumentRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vstorage_key\x18\x02 \x01(\tR\n" +
	"storageKey\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType\x12\x1b\n" +
	"\tbyte_size\x18\x04 \x01(\x03R\bbyteSize\x12\x16\n" +
	"\x06sha256\x18\x05 \x01(\tR\x06sha256\"\x97\x01\n" +
	"\x10DocumentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1f\n" +
	"\vstorage_key\x18\x03 \x01(\tR\n" +
	"storageKey\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\".\n" +
	"\x13GetDashboardRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xff\x01\n" +
	"\x11DashboardResponse\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12)\n" +
	"\x10progress_percent\x18\x02 \x01(\x01R\x0fprogressPercent\x12%\n" +
	"\x0etotal_criteria\x18\x03 \x01(\x05R\rtotalCriteria\x12'\n" +
	"\x0ffilled_criteria\x18\x04 \x01(\x05R\x0efilledCriteria\x12)\n" +
	"\x10overdue_criteria\x18\x05 \x01(\x05R\x0foverdueCriteria\x12.\n" +
	"\x06states\x18\x06 \x03(\v2\x16.health.CriterionStateR\x06states\"\x88\x02\n" +
	"\x0eCriterionState\x12!\n" +
	"\fcriterion_id\x18\x01 \x01(\tR\vcriterionId\x12%\n" +
	"\x0ecriterion_name\x18\x02 \x01(\tR\rcriterionName\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12>\n" +
	"\rlast_event_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vlastEventAt\x12,\n" +
	"\x12last_value_summary\x18\x05 \x01(\tR\x10lastValueSummary\x12&\n" +
	"\x0erecommendation\x18\x06 \x01(\tR\x0erecommendation\"8\n" +
	"\x1dGetUserCriterionStatesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"P\n" +
	"\x1eGetUserCriterionStatesResponse\x12.\n" +
	"\x06states\x18\x01 \x03(\v2\x16.health.CriterionStateR\x06states\"\xc1\x01\n" +
	"\x17SendNotificationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\achannel\x18\x02 \x01(\tR\achannel\x12+\n" +
	"\x11notification_type\x18\x03 \x01(\tR\x10notificationType\x12#\n" +
	"\rtemplate_code\x18\x04 \x01(\tR\ftemplateCode\x12!\n" +
	"\fpayload_json\x18\x05 \x01(\tR\vpayloadJson\"\x1a\n" +
	"\x18SendNotificationResponse2\xea\x05\n" +
	"\rHealthService\x12I\n" +
	"\fListCriteria\x12\x1b.health.ListCriteriaRequest\x1a\x1c.health.ListCriteriaResponse\x12I\n" +
	"\fListLabTests\x12\x1b.health.ListLabTestsRequest\x1a\x1c.health.ListLabTestsResponse\x12N\n" +
	"\x12CreateNumericEvent\x12!.health.CreateNumericEventRequest\x1a\x15.health.EventResponse\x12N\n" +
	"\x12CreateBooleanEvent\x12!.health.CreateBooleanEventRequest\x1a\x15.health.EventResponse\x12P\n" +
	"\x13CreateMarkDoneEvent\x12\".health.CreateMarkDoneEventRequest\x1a\x15.health.EventResponse\x12I\n" +
	"\x0eCreateDocument\x12\x1d.health.CreateDocumentRequest\x1a\x18.health.DocumentResponse\x12F\n" +
	"\fGetDashboard\x12\x1b.health.GetDashboardRequest\x1a\x19.health.DashboardResponse\x12g\n" +
	"\x16GetUserCriterionStates\x12%.health.GetUserCriterionStatesRequest\x1a&.health.GetUserCriterionStatesResponse\x12U\n" +
	"\x10SendNotification\x12\x1f.health.SendNotificationRequest\x1a .health.SendNotificationResponseB3Z1github.com/helthtech/core-health/pkg/proto/healthb\x06proto3"

var (
	file_health_proto_rawDescOnce sync.Once
	file_health_proto_rawDescData []byte
)

func file_health_proto_rawDescGZIP() []byte {
	file_health_proto_rawDescOnce.Do(func() {
		file_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_health_proto_rawDesc), len(file_health_proto_rawDesc)))
	})
	return file_health_proto_rawDescData
}

var file_health_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_health_proto_goTypes = []any{
	(*ListCriteriaRequest)(nil),            // 0: health.ListCriteriaRequest
	(*Criterion)(nil),                      // 1: health.Criterion
	(*ListCriteriaResponse)(nil),           // 2: health.ListCriteriaResponse
	(*ListLabTestsRequest)(nil),            // 3: health.ListLabTestsRequest
	(*LabTest)(nil),                        // 4: health.LabTest
	(*ListLabTestsResponse)(nil),           // 5: health.ListLabTestsResponse
	(*CreateNumericEventRequest)(nil),      // 6: health.CreateNumericEventRequest
	(*CreateBooleanEventRequest)(nil),      // 7: health.CreateBooleanEventRequest
	(*CreateMarkDoneEventRequest)(nil),     // 8: health.CreateMarkDoneEventRequest
	(*EventResponse)(nil),                  // 9: health.EventResponse
	(*CreateDocumentRequest)(nil),          // 10: health.CreateDocumentRequest
	(*DocumentResponse)(nil),               // 11: health.DocumentResponse
	(*GetDashboardRequest)(nil),            // 12: health.GetDashboardRequest
	(*DashboardResponse)(nil),              // 13: health.DashboardResponse
	(*CriterionState)(nil),                 // 14: health.CriterionState
	(*GetUserCriterionStatesRequest)(nil),  // 15: health.GetUserCriterionStatesRequest
	(*GetUserCriterionStatesResponse)(nil), // 16: health.GetUserCriterionStatesResponse
	(*SendNotificationRequest)(nil),        // 17: health.SendNotificationRequest
	(*SendNotificationResponse)(nil),       // 18: health.SendNotificationResponse
	(*timestamppb.Timestamp)(nil),          // 19: google.protobuf.Timestamp
}
var file_health_proto_depIdxs = []int32{
	1,  // 0: health.ListCriteriaResponse.criteria:type_name -> health.Criterion
	4,  // 1: health.ListLabTestsResponse.lab_tests:type_name -> health.LabTest
	19, // 2: health.CreateNumericEventRequest.occurred_at:type_name -> google.protobuf.Timestamp
	19, // 3: health.CreateBooleanEventRequest.occurred_at:type_name -> google.protobuf.Timestamp
	19, // 4: health.CreateMarkDoneEventRequest.occurred_at:type_name -> google.protobuf.Timestamp
	19, // 5: health.EventResponse.occurred_at:type_name -> google.protobuf.Timestamp
	19, // 6: health.EventResponse.recorded_at:type_name -> google.protobuf.Timestamp
	19, // 7: health.DocumentResponse.created_at:type_name -> google.protobuf.Timestamp
	14, // 8: health.DashboardResponse.states:type_name -> health.CriterionState
	19, // 9: health.CriterionState.last_event_at:type_name -> google.protobuf.Timestamp
	14, // 10: health.GetUserCriterionStatesResponse.states:type_name -> health.CriterionState
	0,  // 11: health.HealthService.ListCriteria:input_type -> health.ListCriteriaRequest
	3,  // 12: health.HealthService.ListLabTests:input_type -> health.ListLabTestsRequest
	6,  // 13: health.HealthService.CreateNumericEvent:input_type -> health.CreateNumericEventRequest
	7,  // 14: health.HealthService.CreateBooleanEvent:input_type -> health.CreateBooleanEventRequest
	8,  // 15: health.HealthService.CreateMarkDoneEvent:input_type -> health.CreateMarkDoneEventRequest
	10, // 16: health.HealthService.CreateDocument:input_type -> health.CreateDocumentRequest
	12, // 17: health.HealthService.GetDashboard:input_type -> health.GetDashboardRequest
	15, // 18: health.HealthService.GetUserCriterionStates:input_type -> health.GetUserCriterionStatesRequest
	17, // 19: health.HealthService.SendNotification:input_type -> health.SendNotificationRequest
	2,  // 20: health.HealthService.ListCriteria:output_type -> health.ListCriteriaResponse
	5,  // 21: health.HealthService.ListLabTests:output_type -> health.ListLabTestsResponse
	9,  // 22: health.HealthService.CreateNumericEvent:output_type -> health.EventResponse
	9,  // 23: health.HealthService.CreateBooleanEvent:output_type -> health.EventResponse
	9,  // 24: health.HealthService.CreateMarkDoneEvent:output_type -> health.EventResponse
	11, // 25: health.HealthService.CreateDocument:output_type -> health.DocumentResponse
	13, // 26: health.HealthService.GetDashboard:output_type -> health.DashboardResponse
	16, // 27: health.HealthService.GetUserCriterionStates:output_type -> health.GetUserCriterionStatesResponse
	18, // 28: health.HealthService.SendNotification:output_type -> health.SendNotificationResponse
	20, // [20:29] is the sub-list for method output_type
	11, // [11:20] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_health_proto_init() }
func file_health_proto_init() {
	if File_health_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_health_proto_rawDesc), len(file_health_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_health_proto_goTypes,
		DependencyIndexes: file_health_proto_depIdxs,
		MessageInfos:      file_health_proto_msgTypes,
	}.Build()
	File_health_proto = out.File
	file_health_proto_goTypes = nil
	file_health_proto_depIdxs = nil
}
