// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: health.proto

package health

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HealthService_ListCriteria_FullMethodName       = "/health.HealthService/ListCriteria"
	HealthService_SetUserCriterion_FullMethodName   = "/health.HealthService/SetUserCriterion"
	HealthService_ResetCriteria_FullMethodName      = "/health.HealthService/ResetCriteria"
	HealthService_GetUserCriteria_FullMethodName    = "/health.HealthService/GetUserCriteria"
	HealthService_GetProgress_FullMethodName        = "/health.HealthService/GetProgress"
	HealthService_GetRecommendations_FullMethodName = "/health.HealthService/GetRecommendations"
	HealthService_SendNotification_FullMethodName   = "/health.HealthService/SendNotification"
)

// HealthServiceClient is the client API for HealthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HealthServiceClient interface {
	ListCriteria(ctx context.Context, in *ListCriteriaRequest, opts ...grpc.CallOption) (*ListCriteriaResponse, error)
	SetUserCriterion(ctx context.Context, in *SetUserCriterionRequest, opts ...grpc.CallOption) (*SetUserCriterionResponse, error)
	ResetCriteria(ctx context.Context, in *ResetCriteriaRequest, opts ...grpc.CallOption) (*ResetCriteriaResponse, error)
	GetUserCriteria(ctx context.Context, in *GetUserCriteriaRequest, opts ...grpc.CallOption) (*GetUserCriteriaResponse, error)
	GetProgress(ctx context.Context, in *GetProgressRequest, opts ...grpc.CallOption) (*GetProgressResponse, error)
	GetRecommendations(ctx context.Context, in *GetRecommendationsRequest, opts ...grpc.CallOption) (*GetRecommendationsResponse, error)
	SendNotification(ctx context.Context, in *SendNotificationRequest, opts ...grpc.CallOption) (*SendNotificationResponse, error)
}

type healthServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHealthServiceClient(cc grpc.ClientConnInterface) HealthServiceClient {
	return &healthServiceClient{cc}
}

func (c *healthServiceClient) ListCriteria(ctx context.Context, in *ListCriteriaRequest, opts ...grpc.CallOption) (*ListCriteriaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCriteriaResponse)
	err := c.cc.Invoke(ctx, HealthService_ListCriteria_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthServiceClient) SetUserCriterion(ctx context.Context, in *SetUserCriterionRequest, opts ...grpc.CallOption) (*SetUserCriterionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetUserCriterionResponse)
	err := c.cc.Invoke(ctx, HealthService_SetUserCriterion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthServiceClient) ResetCriteria(ctx context.Context, in *ResetCriteriaRequest, opts ...grpc.CallOption) (*ResetCriteriaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetCriteriaResponse)
	err := c.cc.Invoke(ctx, HealthService_ResetCriteria_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthServiceClient) GetUserCriteria(ctx context.Context, in *GetUserCriteriaRequest, opts ...grpc.CallOption) (*GetUserCriteriaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserCriteriaResponse)
	err := c.cc.Invoke(ctx, HealthService_GetUserCriteria_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthServiceClient) GetProgress(ctx context.Context, in *GetProgressRequest, opts ...grpc.CallOption) (*GetProgressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProgressResponse)
	err := c.cc.Invoke(ctx, HealthService_GetProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthServiceClient) GetRecommendations(ctx context.Context, in *GetRecommendationsRequest, opts ...grpc.CallOption) (*GetRecommendationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRecommendationsResponse)
	err := c.cc.Invoke(ctx, HealthService_GetRecommendations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthServiceClient) SendNotification(ctx context.Context, in *SendNotificationRequest, opts ...grpc.CallOption) (*SendNotificationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendNotificationResponse)
	err := c.cc.Invoke(ctx, HealthService_SendNotification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HealthServiceServer is the server API for HealthService service.
// All implementations must embed UnimplementedHealthServiceServer
// for forward compatibility.
type HealthServiceServer interface {
	ListCriteria(context.Context, *ListCriteriaRequest) (*ListCriteriaResponse, error)
	SetUserCriterion(context.Context, *SetUserCriterionRequest) (*SetUserCriterionResponse, error)
	ResetCriteria(context.Context, *ResetCriteriaRequest) (*ResetCriteriaResponse, error)
	GetUserCriteria(context.Context, *GetUserCriteriaRequest) (*GetUserCriteriaResponse, error)
	GetProgress(context.Context, *GetProgressRequest) (*GetProgressResponse, error)
	GetRecommendations(context.Context, *GetRecommendationsRequest) (*GetRecommendationsResponse, error)
	SendNotification(context.Context, *SendNotificationRequest) (*SendNotificationResponse, error)
	mustEmbedUnimplementedHealthServiceServer()
}

// UnimplementedHealthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHealthServiceServer struct{}

func (UnimplementedHealthServiceServer) ListCriteria(context.Context, *ListCriteriaRequest) (*ListCriteriaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCriteria not implemented")
}
func (UnimplementedHealthServiceServer) SetUserCriterion(context.Context, *SetUserCriterionRequest) (*SetUserCriterionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetUserCriterion not implemented")
}
func (UnimplementedHealthServiceServer) ResetCriteria(context.Context, *ResetCriteriaRequest) (*ResetCriteriaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResetCriteria not implemented")
}
func (UnimplementedHealthServiceServer) GetUserCriteria(context.Context, *GetUserCriteriaRequest) (*GetUserCriteriaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserCriteria not implemented")
}
func (UnimplementedHealthServiceServer) GetProgress(context.Context, *GetProgressRequest) (*GetProgressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProgress not implemented")
}
func (UnimplementedHealthServiceServer) GetRecommendations(context.Context, *GetRecommendationsRequest) (*GetRecommendationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRecommendations not implemented")
}
func (UnimplementedHealthServiceServer) SendNotification(context.Context, *SendNotificationRequest) (*SendNotificationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendNotification not implemented")
}
func (UnimplementedHealthServiceServer) mustEmbedUnimplementedHealthServiceServer() {}
func (UnimplementedHealthServiceServer) testEmbeddedByValue()                       {}

// UnsafeHealthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HealthServiceServer will
// result in compilation errors.
type UnsafeHealthServiceServer interface {
	mustEmbedUnimplementedHealthServiceServer()
}

func RegisterHealthServiceServer(s grpc.ServiceRegistrar, srv HealthServiceServer) {
	// If the following call panics, it indicates UnimplementedHealthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HealthService_ServiceDesc, srv)
}

func _HealthService_ListCriteria_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCriteriaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServiceServer).ListCriteria(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthService_ListCriteria_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServiceServer).ListCriteria(ctx, req.(*ListCriteriaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HealthService_SetUserCriterion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUserCriterionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServiceServer).SetUserCriterion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthService_SetUserCriterion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServiceServer).SetUserCriterion(ctx, req.(*SetUserCriterionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HealthService_ResetCriteria_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetCriteriaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServiceServer).ResetCriteria(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthService_ResetCriteria_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServiceServer).ResetCriteria(ctx, req.(*ResetCriteriaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HealthService_GetUserCriteria_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserCriteriaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServiceServer).GetUserCriteria(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthService_GetUserCriteria_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServiceServer).GetUserCriteria(ctx, req.(*GetUserCriteriaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HealthService_GetProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServiceServer).GetProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthService_GetProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServiceServer).GetProgress(ctx, req.(*GetProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HealthService_GetRecommendations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecommendationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServiceServer).GetRecommendations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthService_GetRecommendations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServiceServer).GetRecommendations(ctx, req.(*GetRecommendationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HealthService_SendNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServiceServer).SendNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthService_SendNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServiceServer).SendNotification(ctx, req.(*SendNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HealthService_ServiceDesc is the grpc.ServiceDesc for HealthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HealthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "health.HealthService",
	HandlerType: (*HealthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListCriteria",
			Handler:    _HealthService_ListCriteria_Handler,
		},
		{
			MethodName: "SetUserCriterion",
			Handler:    _HealthService_SetUserCriterion_Handler,
		},
		{
			MethodName: "ResetCriteria",
			Handler:    _HealthService_ResetCriteria_Handler,
		},
		{
			MethodName: "GetUserCriteria",
			Handler:    _HealthService_GetUserCriteria_Handler,
		},
		{
			MethodName: "GetProgress",
			Handler:    _HealthService_GetProgress_Handler,
		},
		{
			MethodName: "GetRecommendations",
			Handler:    _HealthService_GetRecommendations_Handler,
		},
		{
			MethodName: "SendNotification",
			Handler:    _HealthService_SendNotification_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "health.proto",
}
