// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: health.proto

package health

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Analysis struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// lifetime in days; 0 means no expiry
	Lifetime int32 `protobuf:"varint,3,opt,name=lifetime,proto3" json:"lifetime,omitempty"`
	// sex restriction: "male", "female", or "" for all
	Sex string `protobuf:"bytes,4,opt,name=sex,proto3" json:"sex,omitempty"`
	// blocked_by: "", "level_1", "level_2", or "criteria_<uuid>"
	BlockedBy     string `protobuf:"bytes,5,opt,name=blocked_by,json=blockedBy,proto3" json:"blocked_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Analysis) Reset() {
	*x = Analysis{}
	mi := &file_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Analysis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Analysis) ProtoMessage() {}

func (x *Analysis) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Analysis.ProtoReflect.Descriptor instead.
func (*Analysis) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{0}
}

func (x *Analysis) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Analysis) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Analysis) GetLifetime() int32 {
	if x != nil {
		return x.Lifetime
	}
	return 0
}

func (x *Analysis) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

func (x *Analysis) GetBlockedBy() string {
	if x != nil {
		return x.BlockedBy
	}
	return ""
}

// ListAnalysisRequest optionally filters by user context (sex + blocking rules).
type ListAnalysisRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserSex       string                 `protobuf:"bytes,2,opt,name=user_sex,json=userSex,proto3" json:"user_sex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAnalysisRequest) Reset() {
	*x = ListAnalysisRequest{}
	mi := &file_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAnalysisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAnalysisRequest) ProtoMessage() {}

func (x *ListAnalysisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAnalysisRequest.ProtoReflect.Descriptor instead.
func (*ListAnalysisRequest) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{1}
}

func (x *ListAnalysisRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListAnalysisRequest) GetUserSex() string {
	if x != nil {
		return x.UserSex
	}
	return ""
}

type ListAnalysisResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Analyses      []*Analysis            `protobuf:"bytes,1,rep,name=analyses,proto3" json:"analyses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAnalysisResponse) Reset() {
	*x = ListAnalysisResponse{}
	mi := &file_health_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAnalysisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAnalysisResponse) ProtoMessage() {}

func (x *ListAnalysisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAnalysisResponse.ProtoReflect.Descriptor instead.
func (*ListAnalysisResponse) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{2}
}

func (x *ListAnalysisResponse) GetAnalyses() []*Analysis {
	if x != nil {
		return x.Analyses
	}
	return nil
}

type Criterion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AnalysisId    string                 `protobuf:"bytes,3,opt,name=analysis_id,json=analysisId,proto3" json:"analysis_id,omitempty"`
	Level         int32                  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Criterion) Reset() {
	*x = Criterion{}
	mi := &file_health_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Criterion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Criterion) ProtoMessage() {}

func (x *Criterion) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Criterion.ProtoReflect.Descriptor instead.
func (*Criterion) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{3}
}

func (x *Criterion) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Criterion) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Criterion) GetAnalysisId() string {
	if x != nil {
		return x.AnalysisId
	}
	return ""
}

func (x *Criterion) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type ListCriteriaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AnalysisId    string                 `protobuf:"bytes,1,opt,name=analysis_id,json=analysisId,proto3" json:"analysis_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCriteriaRequest) Reset() {
	*x = ListCriteriaRequest{}
	mi := &file_health_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCriteriaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCriteriaRequest) ProtoMessage() {}

func (x *ListCriteriaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCriteriaRequest.ProtoReflect.Descriptor instead.
func (*ListCriteriaRequest) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{4}
}

func (x *ListCriteriaRequest) GetAnalysisId() string {
	if x != nil {
		return x.AnalysisId
	}
	return ""
}

type ListCriteriaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Criteria      []*Criterion           `protobuf:"bytes,1,rep,name=criteria,proto3" json:"criteria,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCriteriaResponse) Reset() {
	*x = ListCriteriaResponse{}
	mi := &file_health_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCriteriaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCriteriaResponse) ProtoMessage() {}

func (x *ListCriteriaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCriteriaResponse.ProtoReflect.Descriptor instead.
func (*ListCriteriaResponse) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{5}
}

func (x *ListCriteriaResponse) GetCriteria() []*Criterion {
	if x != nil {
		return x.Criteria
	}
	return nil
}

type SetUserCriterionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CriterionId   string                 `protobuf:"bytes,2,opt,name=criterion_id,json=criterionId,proto3" json:"criterion_id,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserCriterionRequest) Reset() {
	*x = SetUserCriterionRequest{}
	mi := &file_health_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserCriterionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserCriterionRequest) ProtoMessage() {}

func (x *SetUserCriterionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserCriterionRequest.ProtoReflect.Descriptor instead.
func (*SetUserCriterionRequest) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{6}
}

func (x *SetUserCriterionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SetUserCriterionRequest) GetCriterionId() string {
	if x != nil {
		return x.CriterionId
	}
	return ""
}

func (x *SetUserCriterionRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SetUserCriterionRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type SetUserCriterionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserCriterionResponse) Reset() {
	*x = SetUserCriterionResponse{}
	mi := &file_health_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserCriterionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserCriterionResponse) ProtoMessage() {}

func (x *SetUserCriterionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserCriterionResponse.ProtoReflect.Descriptor instead.
func (*SetUserCriterionResponse) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{7}
}

func (x *SetUserCriterionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UserCriterionEntry struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CriterionId    string                 `protobuf:"bytes,1,opt,name=criterion_id,json=criterionId,proto3" json:"criterion_id,omitempty"`
	CriterionName  string                 `protobuf:"bytes,2,opt,name=criterion_name,json=criterionName,proto3" json:"criterion_name,omitempty"`
	AnalysisId     string                 `protobuf:"bytes,3,opt,name=analysis_id,json=analysisId,proto3" json:"analysis_id,omitempty"`
	AnalysisName   string                 `protobuf:"bytes,4,opt,name=analysis_name,json=analysisName,proto3" json:"analysis_name,omitempty"`
	Value          string                 `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	Status         string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Recommendation string                 `protobuf:"bytes,7,opt,name=recommendation,proto3" json:"recommendation,omitempty"`
	Level          int32                  `protobuf:"varint,8,opt,name=level,proto3" json:"level,omitempty"`
	Severity       string                 `protobuf:"bytes,9,opt,name=severity,proto3" json:"severity,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserCriterionEntry) Reset() {
	*x = UserCriterionEntry{}
	mi := &file_health_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCriterionEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCriterionEntry) ProtoMessage() {}

func (x *UserCriterionEntry) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCriterionEntry.ProtoReflect.Descriptor instead.
func (*UserCriterionEntry) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{8}
}

func (x *UserCriterionEntry) GetCriterionId() string {
	if x != nil {
		return x.CriterionId
	}
	return ""
}

func (x *UserCriterionEntry) GetCriterionName() string {
	if x != nil {
		return x.CriterionName
	}
	return ""
}

func (x *UserCriterionEntry) GetAnalysisId() string {
	if x != nil {
		return x.AnalysisId
	}
	return ""
}

func (x *UserCriterionEntry) GetAnalysisName() string {
	if x != nil {
		return x.AnalysisName
	}
	return ""
}

func (x *UserCriterionEntry) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *UserCriterionEntry) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UserCriterionEntry) GetRecommendation() string {
	if x != nil {
		return x.Recommendation
	}
	return ""
}

func (x *UserCriterionEntry) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *UserCriterionEntry) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

type GetUserCriteriaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserSex       string                 `protobuf:"bytes,2,opt,name=user_sex,json=userSex,proto3" json:"user_sex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserCriteriaRequest) Reset() {
	*x = GetUserCriteriaRequest{}
	mi := &file_health_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserCriteriaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserCriteriaRequest) ProtoMessage() {}

func (x *GetUserCriteriaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserCriteriaRequest.ProtoReflect.Descriptor instead.
func (*GetUserCriteriaRequest) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserCriteriaRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserCriteriaRequest) GetUserSex() string {
	if x != nil {
		return x.UserSex
	}
	return ""
}

type GetUserCriteriaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*UserCriterionEntry  `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserCriteriaResponse) Reset() {
	*x = GetUserCriteriaResponse{}
	mi := &file_health_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserCriteriaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserCriteriaResponse) ProtoMessage() {}

func (x *GetUserCriteriaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserCriteriaResponse.ProtoReflect.Descriptor instead.
func (*GetUserCriteriaResponse) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{10}
}

func (x *GetUserCriteriaResponse) GetEntries() []*UserCriterionEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type GetProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProgressRequest) Reset() {
	*x = GetProgressRequest{}
	mi := &file_health_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProgressRequest) ProtoMessage() {}

func (x *GetProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProgressRequest.ProtoReflect.Descriptor instead.
func (*GetProgressRequest) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{11}
}

func (x *GetProgressRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetProgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Filled        int32                  `protobuf:"varint,2,opt,name=filled,proto3" json:"filled,omitempty"`
	Percent       float64                `protobuf:"fixed64,3,opt,name=percent,proto3" json:"percent,omitempty"`
	LevelLabel    string                 `protobuf:"bytes,4,opt,name=level_label,json=levelLabel,proto3" json:"level_label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProgressResponse) Reset() {
	*x = GetProgressResponse{}
	mi := &file_health_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProgressResponse) ProtoMessage() {}

func (x *GetProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProgressResponse.ProtoReflect.Descriptor instead.
func (*GetProgressResponse) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{12}
}

func (x *GetProgressResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetProgressResponse) GetFilled() int32 {
	if x != nil {
		return x.Filled
	}
	return 0
}

func (x *GetProgressResponse) GetPercent() float64 {
	if x != nil {
		return x.Percent
	}
	return 0
}

func (x *GetProgressResponse) GetLevelLabel() string {
	if x != nil {
		return x.LevelLabel
	}
	return ""
}

type Recommendation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CriterionId   string                 `protobuf:"bytes,1,opt,name=criterion_id,json=criterionId,proto3" json:"criterion_id,omitempty"`
	CriterionName string                 `protobuf:"bytes,2,opt,name=criterion_name,json=criterionName,proto3" json:"criterion_name,omitempty"`
	AnalysisName  string                 `protobuf:"bytes,3,opt,name=analysis_name,json=analysisName,proto3" json:"analysis_name,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	Severity      string                 `protobuf:"bytes,5,opt,name=severity,proto3" json:"severity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Recommendation) Reset() {
	*x = Recommendation{}
	mi := &file_health_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Recommendation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Recommendation) ProtoMessage() {}

func (x *Recommendation) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Recommendation.ProtoReflect.Descriptor instead.
func (*Recommendation) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{13}
}

func (x *Recommendation) GetCriterionId() string {
	if x != nil {
		return x.CriterionId
	}
	return ""
}

func (x *Recommendation) GetCriterionName() string {
	if x != nil {
		return x.CriterionName
	}
	return ""
}

func (x *Recommendation) GetAnalysisName() string {
	if x != nil {
		return x.AnalysisName
	}
	return ""
}

func (x *Recommendation) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Recommendation) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

type GetRecommendationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserSex       string                 `protobuf:"bytes,2,opt,name=user_sex,json=userSex,proto3" json:"user_sex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecommendationsRequest) Reset() {
	*x = GetRecommendationsRequest{}
	mi := &file_health_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendationsRequest) ProtoMessage() {}

func (x *GetRecommendationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendationsRequest.ProtoReflect.Descriptor instead.
func (*GetRecommendationsRequest) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{14}
}

func (x *GetRecommendationsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetRecommendationsRequest) GetUserSex() string {
	if x != nil {
		return x.UserSex
	}
	return ""
}

type GetRecommendationsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Recommendations []*Recommendation      `protobuf:"bytes,1,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetRecommendationsResponse) Reset() {
	*x = GetRecommendationsResponse{}
	mi := &file_health_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendationsResponse) ProtoMessage() {}

func (x *GetRecommendationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendationsResponse.ProtoReflect.Descriptor instead.
func (*GetRecommendationsResponse) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{15}
}

func (x *GetRecommendationsResponse) GetRecommendations() []*Recommendation {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

type ResetAnalysisCriteriaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AnalysisId    string                 `protobuf:"bytes,2,opt,name=analysis_id,json=analysisId,proto3" json:"analysis_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetAnalysisCriteriaRequest) Reset() {
	*x = ResetAnalysisCriteriaRequest{}
	mi := &file_health_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetAnalysisCriteriaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetAnalysisCriteriaRequest) ProtoMessage() {}

func (x *ResetAnalysisCriteriaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetAnalysisCriteriaRequest.ProtoReflect.Descriptor instead.
func (*ResetAnalysisCriteriaRequest) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{16}
}

func (x *ResetAnalysisCriteriaRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ResetAnalysisCriteriaRequest) GetAnalysisId() string {
	if x != nil {
		return x.AnalysisId
	}
	return ""
}

type ResetAnalysisCriteriaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetAnalysisCriteriaResponse) Reset() {
	*x = ResetAnalysisCriteriaResponse{}
	mi := &file_health_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetAnalysisCriteriaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetAnalysisCriteriaResponse) ProtoMessage() {}

func (x *ResetAnalysisCriteriaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetAnalysisCriteriaResponse.ProtoReflect.Descriptor instead.
func (*ResetAnalysisCriteriaResponse) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{17}
}

func (x *ResetAnalysisCriteriaResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SendNotificationRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Channel          string                 `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	NotificationType string                 `protobuf:"bytes,3,opt,name=notification_type,json=notificationType,proto3" json:"notification_type,omitempty"`
	TemplateCode     string                 `protobuf:"bytes,4,opt,name=template_code,json=templateCode,proto3" json:"template_code,omitempty"`
	PayloadJson      string                 `protobuf:"bytes,5,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SendNotificationRequest) Reset() {
	*x = SendNotificationRequest{}
	mi := &file_health_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationRequest) ProtoMessage() {}

func (x *SendNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationRequest.ProtoReflect.Descriptor instead.
func (*SendNotificationRequest) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{18}
}

func (x *SendNotificationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SendNotificationRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *SendNotificationRequest) GetNotificationType() string {
	if x != nil {
		return x.NotificationType
	}
	return ""
}

func (x *SendNotificationRequest) GetTemplateCode() string {
	if x != nil {
		return x.TemplateCode
	}
	return ""
}

func (x *SendNotificationRequest) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

type SendNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNotificationResponse) Reset() {
	*x = SendNotificationResponse{}
	mi := &file_health_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationResponse) ProtoMessage() {}

func (x *SendNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_health_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationResponse.ProtoReflect.Descriptor instead.
func (*SendNotificationResponse) Descriptor() ([]byte, []int) {
	return file_health_proto_rawDescGZIP(), []int{19}
}

var File_health_proto protoreflect.FileDescriptor

const file_health_proto_rawDesc = "" +
	"\n" +
	"\fhealth.proto\x12\x06health\"{\n" +
	"\bAnalysis\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\blifetime\x18\x03 \x01(\x05R\blifetime\x12\x10\n" +
	"\x03sex\x18\x04 \x01(\tR\x03sex\x12\x1d\n" +
	"\n" +
	"blocked_by\x18\x05 \x01(\tR\tblockedBy\"I\n" +
	"\x13ListAnalysisRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\buser_sex\x18\x02 \x01(\tR\auserSex\"D\n" +
	"\x14ListAnalysisResponse\x12,\n" +
	"\banalyses\x18\x01 \x03(\v2\x10.health.AnalysisR\banalyses\"f\n" +
	"\tCriterion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vanalysis_id\x18\x03 \x01(\tR\n" +
	"analysisId\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level\"6\n" +
	"\x13ListCriteriaRequest\x12\x1f\n" +
	"\vanalysis_id\x18\x01 \x01(\tR\n" +
	"analysisId\"E\n" +
	"\x14ListCriteriaResponse\x12-\n" +
	"\bcriteria\x18\x01 \x03(\v2\x11.health.CriterionR\bcriteria\"\x83\x01\n" +
	"\x17SetUserCriterionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fcriterion_id\x18\x02 \x01(\tR\vcriterionId\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\"4\n" +
	"\x18SetUserCriterionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xac\x02\n" +
	"\x12UserCriterionEntry\x12!\n" +
	"\fcriterion_id\x18\x01 \x01(\tR\vcriterionId\x12%\n" +
	"\x0ecriterion_name\x18\x02 \x01(\tR\rcriterionName\x12\x1f\n" +
	"\vanalysis_id\x18\x03 \x01(\tR\n" +
	"analysisId\x12#\n" +
	"\ranalysis_name\x18\x04 \x01(\tR\fanalysisName\x12\x14\n" +
	"\x05value\x18\x05 \x01(\tR\x05value\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12&\n" +
	"\x0erecommendation\x18\a \x01(\tR\x0erecommendation\x12\x14\n" +
	"\x05level\x18\b \x01(\x05R\x05level\x12\x1a\n" +
	"\bseverity\x18\t \x01(\tR\bseverity\"L\n" +
	"\x16GetUserCriteriaRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\buser_sex\x18\x02 \x01(\tR\auserSex\"O\n" +
	"\x17GetUserCriteriaResponse\x124\n" +
	"\aentries\x18\x01 \x03(\v2\x1a.health.UserCriterionEntryR\aentries\"-\n" +
	"\x12GetProgressRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"~\n" +
	"\x13GetProgressResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x16\n" +
	"\x06filled\x18\x02 \x01(\x05R\x06filled\x12\x18\n" +
	"\apercent\x18\x03 \x01(\x01R\apercent\x12\x1f\n" +
	"\vlevel_label\x18\x04 \x01(\tR\n" +
	"levelLabel\"\xaf\x01\n" +
	"\x0eRecommendation\x12!\n" +
	"\fcriterion_id\x18\x01 \x01(\tR\vcriterionId\x12%\n" +
	"\x0ecriterion_name\x18\x02 \x01(\tR\rcriterionName\x12#\n" +
	"\ranalysis_name\x18\x03 \x01(\tR\fanalysisName\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12\x1a\n" +
	"\bseverity\x18\x05 \x01(\tR\bseverity\"O\n" +
	"\x19GetRecommendationsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\buser_sex\x18\x02 \x01(\tR\auserSex\"^\n" +
	"\x1aGetRecommendationsResponse\x12@\n" +
	"\x0frecommendations\x18\x01 \x03(\v2\x16.health.RecommendationR\x0frecommendations\"X\n" +
	"\x1cResetAnalysisCriteriaRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vanalysis_id\x18\x02 \x01(\tR\n" +
	"analysisId\"9\n" +
	"\x1dResetAnalysisCriteriaResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xc1\x01\n" +
	"\x17SendNotificationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\achannel\x18\x02 \x01(\tR\achannel\x12+\n" +
	"\x11notification_type\x18\x03 \x01(\tR\x10notificationType\x12#\n" +
	"\rtemplate_code\x18\x04 \x01(\tR\ftemplateCode\x12!\n" +
	"\fpayload_json\x18\x05 \x01(\tR\vpayloadJson\"\x1a\n" +
	"\x18SendNotificationResponse2\xb2\x05\n" +
	"\rHealthService\x12I\n" +
	"\fListAnalysis\x12\x1b.health.ListAnalysisRequest\x1a\x1c.health.ListAnalysisResponse\x12I\n" +
	"\fListCriteria\x12\x1b.health.ListCriteriaRequest\x1a\x1c.health.ListCriteriaResponse\x12U\n" +
	"\x10SetUserCriterion\x12\x1f.health.SetUserCriterionRequest\x1a .health.SetUserCriterionResponse\x12d\n" +
	"\x15ResetAnalysisCriteria\x12$.health.ResetAnalysisCriteriaRequest\x1a%.health.ResetAnalysisCriteriaResponse\x12R\n" +
	"\x0fGetUserCriteria\x12\x1e.health.GetUserCriteriaRequest\x1a\x1f.health.GetUserCriteriaResponse\x12F\n" +
	"\vGetProgress\x12\x1a.health.GetProgressRequest\x1a\x1b.health.GetProgressResponse\x12[\n" +
	"\x12GetRecommendations\x12!.health.GetRecommendationsRequest\x1a\".health.GetRecommendationsResponse\x12U\n" +
	"\x10SendNotification\x12\x1f.health.SendNotificationRequest\x1a .health.SendNotificationResponseB3Z1github.com/helthtech/core-health/pkg/proto/healthb\x06proto3"

var (
	file_health_proto_rawDescOnce sync.Once
	file_health_proto_rawDescData []byte
)

func file_health_proto_rawDescGZIP() []byte {
	file_health_proto_rawDescOnce.Do(func() {
		file_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_health_proto_rawDesc), len(file_health_proto_rawDesc)))
	})
	return file_health_proto_rawDescData
}

var file_health_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_health_proto_goTypes = []any{
	(*Analysis)(nil),                      // 0: health.Analysis
	(*ListAnalysisRequest)(nil),           // 1: health.ListAnalysisRequest
	(*ListAnalysisResponse)(nil),          // 2: health.ListAnalysisResponse
	(*Criterion)(nil),                     // 3: health.Criterion
	(*ListCriteriaRequest)(nil),           // 4: health.ListCriteriaRequest
	(*ListCriteriaResponse)(nil),          // 5: health.ListCriteriaResponse
	(*SetUserCriterionRequest)(nil),       // 6: health.SetUserCriterionRequest
	(*SetUserCriterionResponse)(nil),      // 7: health.SetUserCriterionResponse
	(*UserCriterionEntry)(nil),            // 8: health.UserCriterionEntry
	(*GetUserCriteriaRequest)(nil),        // 9: health.GetUserCriteriaRequest
	(*GetUserCriteriaResponse)(nil),       // 10: health.GetUserCriteriaResponse
	(*GetProgressRequest)(nil),            // 11: health.GetProgressRequest
	(*GetProgressResponse)(nil),           // 12: health.GetProgressResponse
	(*Recommendation)(nil),                // 13: health.Recommendation
	(*GetRecommendationsRequest)(nil),     // 14: health.GetRecommendationsRequest
	(*GetRecommendationsResponse)(nil),    // 15: health.GetRecommendationsResponse
	(*ResetAnalysisCriteriaRequest)(nil),  // 16: health.ResetAnalysisCriteriaRequest
	(*ResetAnalysisCriteriaResponse)(nil), // 17: health.ResetAnalysisCriteriaResponse
	(*SendNotificationRequest)(nil),       // 18: health.SendNotificationRequest
	(*SendNotificationResponse)(nil),      // 19: health.SendNotificationResponse
}
var file_health_proto_depIdxs = []int32{
	0,  // 0: health.ListAnalysisResponse.analyses:type_name -> health.Analysis
	3,  // 1: health.ListCriteriaResponse.criteria:type_name -> health.Criterion
	8,  // 2: health.GetUserCriteriaResponse.entries:type_name -> health.UserCriterionEntry
	13, // 3: health.GetRecommendationsResponse.recommendations:type_name -> health.Recommendation
	1,  // 4: health.HealthService.ListAnalysis:input_type -> health.ListAnalysisRequest
	4,  // 5: health.HealthService.ListCriteria:input_type -> health.ListCriteriaRequest
	6,  // 6: health.HealthService.SetUserCriterion:input_type -> health.SetUserCriterionRequest
	16, // 7: health.HealthService.ResetAnalysisCriteria:input_type -> health.ResetAnalysisCriteriaRequest
	9,  // 8: health.HealthService.GetUserCriteria:input_type -> health.GetUserCriteriaRequest
	11, // 9: health.HealthService.GetProgress:input_type -> health.GetProgressRequest
	14, // 10: health.HealthService.GetRecommendations:input_type -> health.GetRecommendationsRequest
	18, // 11: health.HealthService.SendNotification:input_type -> health.SendNotificationRequest
	2,  // 12: health.HealthService.ListAnalysis:output_type -> health.ListAnalysisResponse
	5,  // 13: health.HealthService.ListCriteria:output_type -> health.ListCriteriaResponse
	7,  // 14: health.HealthService.SetUserCriterion:output_type -> health.SetUserCriterionResponse
	17, // 15: health.HealthService.ResetAnalysisCriteria:output_type -> health.ResetAnalysisCriteriaResponse
	10, // 16: health.HealthService.GetUserCriteria:output_type -> health.GetUserCriteriaResponse
	12, // 17: health.HealthService.GetProgress:output_type -> health.GetProgressResponse
	15, // 18: health.HealthService.GetRecommendations:output_type -> health.GetRecommendationsResponse
	19, // 19: health.HealthService.SendNotification:output_type -> health.SendNotificationResponse
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_health_proto_init() }
func file_health_proto_init() {
	if File_health_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_health_proto_rawDesc), len(file_health_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_health_proto_goTypes,
		DependencyIndexes: file_health_proto_depIdxs,
		MessageInfos:      file_health_proto_msgTypes,
	}.Build()
	File_health_proto = out.File
	file_health_proto_goTypes = nil
	file_health_proto_depIdxs = nil
}
