// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: health.proto

package health

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HealthService_ListCriteria_FullMethodName           = "/health.HealthService/ListCriteria"
	HealthService_ListLabTests_FullMethodName           = "/health.HealthService/ListLabTests"
	HealthService_CreateNumericEvent_FullMethodName     = "/health.HealthService/CreateNumericEvent"
	HealthService_CreateBooleanEvent_FullMethodName     = "/health.HealthService/CreateBooleanEvent"
	HealthService_CreateMarkDoneEvent_FullMethodName    = "/health.HealthService/CreateMarkDoneEvent"
	HealthService_CreateDocument_FullMethodName         = "/health.HealthService/CreateDocument"
	HealthService_GetDashboard_FullMethodName           = "/health.HealthService/GetDashboard"
	HealthService_GetUserCriterionStates_FullMethodName = "/health.HealthService/GetUserCriterionStates"
	HealthService_SendNotification_FullMethodName       = "/health.HealthService/SendNotification"
)

// HealthServiceClient is the client API for HealthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HealthServiceClient interface {
	ListCriteria(ctx context.Context, in *ListCriteriaRequest, opts ...grpc.CallOption) (*ListCriteriaResponse, error)
	ListLabTests(ctx context.Context, in *ListLabTestsRequest, opts ...grpc.CallOption) (*ListLabTestsResponse, error)
	CreateNumericEvent(ctx context.Context, in *CreateNumericEventRequest, opts ...grpc.CallOption) (*EventResponse, error)
	CreateBooleanEvent(ctx context.Context, in *CreateBooleanEventRequest, opts ...grpc.CallOption) (*EventResponse, error)
	CreateMarkDoneEvent(ctx context.Context, in *CreateMarkDoneEventRequest, opts ...grpc.CallOption) (*EventResponse, error)
	CreateDocument(ctx context.Context, in *CreateDocumentRequest, opts ...grpc.CallOption) (*DocumentResponse, error)
	GetDashboard(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*DashboardResponse, error)
	GetUserCriterionStates(ctx context.Context, in *GetUserCriterionStatesRequest, opts ...grpc.CallOption) (*GetUserCriterionStatesResponse, error)
	SendNotification(ctx context.Context, in *SendNotificationRequest, opts ...grpc.CallOption) (*SendNotificationResponse, error)
}

type healthServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHealthServiceClient(cc grpc.ClientConnInterface) HealthServiceClient {
	return &healthServiceClient{cc}
}

func (c *healthServiceClient) ListCriteria(ctx context.Context, in *ListCriteriaRequest, opts ...grpc.CallOption) (*ListCriteriaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCriteriaResponse)
	err := c.cc.Invoke(ctx, HealthService_ListCriteria_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthServiceClient) ListLabTests(ctx context.Context, in *ListLabTestsRequest, opts ...grpc.CallOption) (*ListLabTestsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLabTestsResponse)
	err := c.cc.Invoke(ctx, HealthService_ListLabTests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthServiceClient) CreateNumericEvent(ctx context.Context, in *CreateNumericEventRequest, opts ...grpc.CallOption) (*EventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventResponse)
	err := c.cc.Invoke(ctx, HealthService_CreateNumericEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthServiceClient) CreateBooleanEvent(ctx context.Context, in *CreateBooleanEventRequest, opts ...grpc.CallOption) (*EventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventResponse)
	err := c.cc.Invoke(ctx, HealthService_CreateBooleanEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthServiceClient) CreateMarkDoneEvent(ctx context.Context, in *CreateMarkDoneEventRequest, opts ...grpc.CallOption) (*EventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventResponse)
	err := c.cc.Invoke(ctx, HealthService_CreateMarkDoneEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthServiceClient) CreateDocument(ctx context.Context, in *CreateDocumentRequest, opts ...grpc.CallOption) (*DocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DocumentResponse)
	err := c.cc.Invoke(ctx, HealthService_CreateDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthServiceClient) GetDashboard(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*DashboardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DashboardResponse)
	err := c.cc.Invoke(ctx, HealthService_GetDashboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthServiceClient) GetUserCriterionStates(ctx context.Context, in *GetUserCriterionStatesRequest, opts ...grpc.CallOption) (*GetUserCriterionStatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserCriterionStatesResponse)
	err := c.cc.Invoke(ctx, HealthService_GetUserCriterionStates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthServiceClient) SendNotification(ctx context.Context, in *SendNotificationRequest, opts ...grpc.CallOption) (*SendNotificationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendNotificationResponse)
	err := c.cc.Invoke(ctx, HealthService_SendNotification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HealthServiceServer is the server API for HealthService service.
// All implementations must embed UnimplementedHealthServiceServer
// for forward compatibility.
type HealthServiceServer interface {
	ListCriteria(context.Context, *ListCriteriaRequest) (*ListCriteriaResponse, error)
	ListLabTests(context.Context, *ListLabTestsRequest) (*ListLabTestsResponse, error)
	CreateNumericEvent(context.Context, *CreateNumericEventRequest) (*EventResponse, error)
	CreateBooleanEvent(context.Context, *CreateBooleanEventRequest) (*EventResponse, error)
	CreateMarkDoneEvent(context.Context, *CreateMarkDoneEventRequest) (*EventResponse, error)
	CreateDocument(context.Context, *CreateDocumentRequest) (*DocumentResponse, error)
	GetDashboard(context.Context, *GetDashboardRequest) (*DashboardResponse, error)
	GetUserCriterionStates(context.Context, *GetUserCriterionStatesRequest) (*GetUserCriterionStatesResponse, error)
	SendNotification(context.Context, *SendNotificationRequest) (*SendNotificationResponse, error)
	mustEmbedUnimplementedHealthServiceServer()
}

// UnimplementedHealthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHealthServiceServer struct{}

func (UnimplementedHealthServiceServer) ListCriteria(context.Context, *ListCriteriaRequest) (*ListCriteriaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCriteria not implemented")
}
func (UnimplementedHealthServiceServer) ListLabTests(context.Context, *ListLabTestsRequest) (*ListLabTestsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLabTests not implemented")
}
func (UnimplementedHealthServiceServer) CreateNumericEvent(context.Context, *CreateNumericEventRequest) (*EventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNumericEvent not implemented")
}
func (UnimplementedHealthServiceServer) CreateBooleanEvent(context.Context, *CreateBooleanEventRequest) (*EventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBooleanEvent not implemented")
}
func (UnimplementedHealthServiceServer) CreateMarkDoneEvent(context.Context, *CreateMarkDoneEventRequest) (*EventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMarkDoneEvent not implemented")
}
func (UnimplementedHealthServiceServer) CreateDocument(context.Context, *CreateDocumentRequest) (*DocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDocument not implemented")
}
func (UnimplementedHealthServiceServer) GetDashboard(context.Context, *GetDashboardRequest) (*DashboardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDashboard not implemented")
}
func (UnimplementedHealthServiceServer) GetUserCriterionStates(context.Context, *GetUserCriterionStatesRequest) (*GetUserCriterionStatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserCriterionStates not implemented")
}
func (UnimplementedHealthServiceServer) SendNotification(context.Context, *SendNotificationRequest) (*SendNotificationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendNotification not implemented")
}
func (UnimplementedHealthServiceServer) mustEmbedUnimplementedHealthServiceServer() {}
func (UnimplementedHealthServiceServer) testEmbeddedByValue()                       {}

// UnsafeHealthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HealthServiceServer will
// result in compilation errors.
type UnsafeHealthServiceServer interface {
	mustEmbedUnimplementedHealthServiceServer()
}

func RegisterHealthServiceServer(s grpc.ServiceRegistrar, srv HealthServiceServer) {
	// If the following call panics, it indicates UnimplementedHealthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HealthService_ServiceDesc, srv)
}

func _HealthService_ListCriteria_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCriteriaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServiceServer).ListCriteria(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthService_ListCriteria_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServiceServer).ListCriteria(ctx, req.(*ListCriteriaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HealthService_ListLabTests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLabTestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServiceServer).ListLabTests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthService_ListLabTests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServiceServer).ListLabTests(ctx, req.(*ListLabTestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HealthService_CreateNumericEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNumericEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServiceServer).CreateNumericEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthService_CreateNumericEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServiceServer).CreateNumericEvent(ctx, req.(*CreateNumericEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HealthService_CreateBooleanEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBooleanEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServiceServer).CreateBooleanEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthService_CreateBooleanEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServiceServer).CreateBooleanEvent(ctx, req.(*CreateBooleanEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HealthService_CreateMarkDoneEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMarkDoneEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServiceServer).CreateMarkDoneEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthService_CreateMarkDoneEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServiceServer).CreateMarkDoneEvent(ctx, req.(*CreateMarkDoneEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HealthService_CreateDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServiceServer).CreateDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthService_CreateDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServiceServer).CreateDocument(ctx, req.(*CreateDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HealthService_GetDashboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDashboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServiceServer).GetDashboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthService_GetDashboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServiceServer).GetDashboard(ctx, req.(*GetDashboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HealthService_GetUserCriterionStates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserCriterionStatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServiceServer).GetUserCriterionStates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthService_GetUserCriterionStates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServiceServer).GetUserCriterionStates(ctx, req.(*GetUserCriterionStatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HealthService_SendNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServiceServer).SendNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HealthService_SendNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServiceServer).SendNotification(ctx, req.(*SendNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HealthService_ServiceDesc is the grpc.ServiceDesc for HealthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HealthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "health.HealthService",
	HandlerType: (*HealthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListCriteria",
			Handler:    _HealthService_ListCriteria_Handler,
		},
		{
			MethodName: "ListLabTests",
			Handler:    _HealthService_ListLabTests_Handler,
		},
		{
			MethodName: "CreateNumericEvent",
			Handler:    _HealthService_CreateNumericEvent_Handler,
		},
		{
			MethodName: "CreateBooleanEvent",
			Handler:    _HealthService_CreateBooleanEvent_Handler,
		},
		{
			MethodName: "CreateMarkDoneEvent",
			Handler:    _HealthService_CreateMarkDoneEvent_Handler,
		},
		{
			MethodName: "CreateDocument",
			Handler:    _HealthService_CreateDocument_Handler,
		},
		{
			MethodName: "GetDashboard",
			Handler:    _HealthService_GetDashboard_Handler,
		},
		{
			MethodName: "GetUserCriterionStates",
			Handler:    _HealthService_GetUserCriterionStates_Handler,
		},
		{
			MethodName: "SendNotification",
			Handler:    _HealthService_SendNotification_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "health.proto",
}
