// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/health/health.proto

package health

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CriterionGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SortOrder     int32                  `protobuf:"varint,3,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CriterionGroup) Reset() {
	*x = CriterionGroup{}
	mi := &file_api_health_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CriterionGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CriterionGroup) ProtoMessage() {}

func (x *CriterionGroup) ProtoReflect() protoreflect.Message {
	mi := &file_api_health_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CriterionGroup.ProtoReflect.Descriptor instead.
func (*CriterionGroup) Descriptor() ([]byte, []int) {
	return file_api_health_health_proto_rawDescGZIP(), []int{0}
}

func (x *CriterionGroup) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CriterionGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CriterionGroup) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

type ListGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupsRequest) Reset() {
	*x = ListGroupsRequest{}
	mi := &file_api_health_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsRequest) ProtoMessage() {}

func (x *ListGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_health_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListGroupsRequest) Descriptor() ([]byte, []int) {
	return file_api_health_health_proto_rawDescGZIP(), []int{1}
}

type ListGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*CriterionGroup      `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupsResponse) Reset() {
	*x = ListGroupsResponse{}
	mi := &file_api_health_health_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsResponse) ProtoMessage() {}

func (x *ListGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_health_health_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsResponse.ProtoReflect.Descriptor instead.
func (*ListGroupsResponse) Descriptor() ([]byte, []int) {
	return file_api_health_health_proto_rawDescGZIP(), []int{2}
}

func (x *ListGroupsResponse) GetGroups() []*CriterionGroup {
	if x != nil {
		return x.Groups
	}
	return nil
}

// sex: "male", "female", or "" for all
// input_type: "numeric", "check", or "boolean"
// lifetime: days before expiry; 0 = no expiry
// min_value/max_value: normal value range (numeric only); delta: non-critical deviation width
type Criterion struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Level     int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	Sex       string                 `protobuf:"bytes,4,opt,name=sex,proto3" json:"sex,omitempty"`
	InputType string                 `protobuf:"bytes,6,opt,name=input_type,json=inputType,proto3" json:"input_type,omitempty"`
	Lifetime  int32                  `protobuf:"varint,7,opt,name=lifetime,proto3" json:"lifetime,omitempty"`
	GroupId   string                 `protobuf:"bytes,8,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	SortOrder int32                  `protobuf:"varint,9,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	MinValue  *float64               `protobuf:"fixed64,10,opt,name=min_value,json=minValue,proto3,oneof" json:"min_value,omitempty"`
	MaxValue  *float64               `protobuf:"fixed64,11,opt,name=max_value,json=maxValue,proto3,oneof" json:"max_value,omitempty"`
	Delta     *float64               `protobuf:"fixed64,12,opt,name=delta,proto3,oneof" json:"delta,omitempty"`
	// Where to go / how to obtain this measurement (lab, clinic, home device, etc.).
	Instruction   string `protobuf:"bytes,13,opt,name=instruction,proto3" json:"instruction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Criterion) Reset() {
	*x = Criterion{}
	mi := &file_api_health_health_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Criterion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Criterion) ProtoMessage() {}

func (x *Criterion) ProtoReflect() protoreflect.Message {
	mi := &file_api_health_health_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Criterion.ProtoReflect.Descriptor instead.
func (*Criterion) Descriptor() ([]byte, []int) {
	return file_api_health_health_proto_rawDescGZIP(), []int{3}
}

func (x *Criterion) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Criterion) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Criterion) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Criterion) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

func (x *Criterion) GetInputType() string {
	if x != nil {
		return x.InputType
	}
	return ""
}

func (x *Criterion) GetLifetime() int32 {
	if x != nil {
		return x.Lifetime
	}
	return 0
}

func (x *Criterion) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *Criterion) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *Criterion) GetMinValue() float64 {
	if x != nil && x.MinValue != nil {
		return *x.MinValue
	}
	return 0
}

func (x *Criterion) GetMaxValue() float64 {
	if x != nil && x.MaxValue != nil {
		return *x.MaxValue
	}
	return 0
}

func (x *Criterion) GetDelta() float64 {
	if x != nil && x.Delta != nil {
		return *x.Delta
	}
	return 0
}

func (x *Criterion) GetInstruction() string {
	if x != nil {
		return x.Instruction
	}
	return ""
}

type ListCriteriaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserSex       string                 `protobuf:"bytes,2,opt,name=user_sex,json=userSex,proto3" json:"user_sex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCriteriaRequest) Reset() {
	*x = ListCriteriaRequest{}
	mi := &file_api_health_health_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCriteriaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCriteriaRequest) ProtoMessage() {}

func (x *ListCriteriaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_health_health_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCriteriaRequest.ProtoReflect.Descriptor instead.
func (*ListCriteriaRequest) Descriptor() ([]byte, []int) {
	return file_api_health_health_proto_rawDescGZIP(), []int{4}
}

func (x *ListCriteriaRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListCriteriaRequest) GetUserSex() string {
	if x != nil {
		return x.UserSex
	}
	return ""
}

type ListCriteriaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Criteria      []*Criterion           `protobuf:"bytes,1,rep,name=criteria,proto3" json:"criteria,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCriteriaResponse) Reset() {
	*x = ListCriteriaResponse{}
	mi := &file_api_health_health_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCriteriaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCriteriaResponse) ProtoMessage() {}

func (x *ListCriteriaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_health_health_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCriteriaResponse.ProtoReflect.Descriptor instead.
func (*ListCriteriaResponse) Descriptor() ([]byte, []int) {
	return file_api_health_health_proto_rawDescGZIP(), []int{5}
}

func (x *ListCriteriaResponse) GetCriteria() []*Criterion {
	if x != nil {
		return x.Criteria
	}
	return nil
}

type SetUserCriterionRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	UserId      string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CriterionId string                 `protobuf:"bytes,2,opt,name=criterion_id,json=criterionId,proto3" json:"criterion_id,omitempty"`
	Value       string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Source      string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	MeasuredAt  string                 `protobuf:"bytes,5,opt,name=measured_at,json=measuredAt,proto3" json:"measured_at,omitempty"` // ISO 8601 date, optional (e.g. "2025-03-15")
	// Optional; same semantics as GetUserCriteria. Used when building the returned entry (sex-specific criteria).
	UserSex       string `protobuf:"bytes,6,opt,name=user_sex,json=userSex,proto3" json:"user_sex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserCriterionRequest) Reset() {
	*x = SetUserCriterionRequest{}
	mi := &file_api_health_health_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserCriterionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserCriterionRequest) ProtoMessage() {}

func (x *SetUserCriterionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_health_health_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserCriterionRequest.ProtoReflect.Descriptor instead.
func (*SetUserCriterionRequest) Descriptor() ([]byte, []int) {
	return file_api_health_health_proto_rawDescGZIP(), []int{6}
}

func (x *SetUserCriterionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SetUserCriterionRequest) GetCriterionId() string {
	if x != nil {
		return x.CriterionId
	}
	return ""
}

func (x *SetUserCriterionRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SetUserCriterionRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *SetUserCriterionRequest) GetMeasuredAt() string {
	if x != nil {
		return x.MeasuredAt
	}
	return ""
}

func (x *SetUserCriterionRequest) GetUserSex() string {
	if x != nil {
		return x.UserSex
	}
	return ""
}

type SetUserCriterionResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Echo of the updated user row for this criterion (includes instruction). Omitted if criterion is hidden for user_sex.
	Entry         *UserCriterionEntry `protobuf:"bytes,2,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserCriterionResponse) Reset() {
	*x = SetUserCriterionResponse{}
	mi := &file_api_health_health_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserCriterionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserCriterionResponse) ProtoMessage() {}

func (x *SetUserCriterionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_health_health_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserCriterionResponse.ProtoReflect.Descriptor instead.
func (*SetUserCriterionResponse) Descriptor() ([]byte, []int) {
	return file_api_health_health_proto_rawDescGZIP(), []int{7}
}

func (x *SetUserCriterionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetUserCriterionResponse) GetEntry() *UserCriterionEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type ResetCriteriaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetCriteriaRequest) Reset() {
	*x = ResetCriteriaRequest{}
	mi := &file_api_health_health_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetCriteriaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetCriteriaRequest) ProtoMessage() {}

func (x *ResetCriteriaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_health_health_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetCriteriaRequest.ProtoReflect.Descriptor instead.
func (*ResetCriteriaRequest) Descriptor() ([]byte, []int) {
	return file_api_health_health_proto_rawDescGZIP(), []int{8}
}

func (x *ResetCriteriaRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ResetCriteriaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetCriteriaResponse) Reset() {
	*x = ResetCriteriaResponse{}
	mi := &file_api_health_health_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetCriteriaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetCriteriaResponse) ProtoMessage() {}

func (x *ResetCriteriaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_health_health_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetCriteriaResponse.ProtoReflect.Descriptor instead.
func (*ResetCriteriaResponse) Descriptor() ([]byte, []int) {
	return file_api_health_health_proto_rawDescGZIP(), []int{9}
}

func (x *ResetCriteriaResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UserCriterionEntry struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CriterionId    string                 `protobuf:"bytes,1,opt,name=criterion_id,json=criterionId,proto3" json:"criterion_id,omitempty"`
	CriterionName  string                 `protobuf:"bytes,2,opt,name=criterion_name,json=criterionName,proto3" json:"criterion_name,omitempty"`
	Value          string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Recommendation string                 `protobuf:"bytes,5,opt,name=recommendation,proto3" json:"recommendation,omitempty"`
	Level          int32                  `protobuf:"varint,6,opt,name=level,proto3" json:"level,omitempty"`
	Severity       string                 `protobuf:"bytes,7,opt,name=severity,proto3" json:"severity,omitempty"`
	InputType      string                 `protobuf:"bytes,8,opt,name=input_type,json=inputType,proto3" json:"input_type,omitempty"`
	GroupId        string                 `protobuf:"bytes,9,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Instruction    string                 `protobuf:"bytes,10,opt,name=instruction,proto3" json:"instruction,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserCriterionEntry) Reset() {
	*x = UserCriterionEntry{}
	mi := &file_api_health_health_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCriterionEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCriterionEntry) ProtoMessage() {}

func (x *UserCriterionEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_health_health_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCriterionEntry.ProtoReflect.Descriptor instead.
func (*UserCriterionEntry) Descriptor() ([]byte, []int) {
	return file_api_health_health_proto_rawDescGZIP(), []int{10}
}

func (x *UserCriterionEntry) GetCriterionId() string {
	if x != nil {
		return x.CriterionId
	}
	return ""
}

func (x *UserCriterionEntry) GetCriterionName() string {
	if x != nil {
		return x.CriterionName
	}
	return ""
}

func (x *UserCriterionEntry) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *UserCriterionEntry) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UserCriterionEntry) GetRecommendation() string {
	if x != nil {
		return x.Recommendation
	}
	return ""
}

func (x *UserCriterionEntry) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *UserCriterionEntry) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *UserCriterionEntry) GetInputType() string {
	if x != nil {
		return x.InputType
	}
	return ""
}

func (x *UserCriterionEntry) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *UserCriterionEntry) GetInstruction() string {
	if x != nil {
		return x.Instruction
	}
	return ""
}

type GetUserCriteriaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserSex       string                 `protobuf:"bytes,2,opt,name=user_sex,json=userSex,proto3" json:"user_sex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserCriteriaRequest) Reset() {
	*x = GetUserCriteriaRequest{}
	mi := &file_api_health_health_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserCriteriaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserCriteriaRequest) ProtoMessage() {}

func (x *GetUserCriteriaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_health_health_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserCriteriaRequest.ProtoReflect.Descriptor instead.
func (*GetUserCriteriaRequest) Descriptor() ([]byte, []int) {
	return file_api_health_health_proto_rawDescGZIP(), []int{11}
}

func (x *GetUserCriteriaRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserCriteriaRequest) GetUserSex() string {
	if x != nil {
		return x.UserSex
	}
	return ""
}

type GetUserCriteriaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*UserCriterionEntry  `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserCriteriaResponse) Reset() {
	*x = GetUserCriteriaResponse{}
	mi := &file_api_health_health_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserCriteriaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserCriteriaResponse) ProtoMessage() {}

func (x *GetUserCriteriaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_health_health_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserCriteriaResponse.ProtoReflect.Descriptor instead.
func (*GetUserCriteriaResponse) Descriptor() ([]byte, []int) {
	return file_api_health_health_proto_rawDescGZIP(), []int{12}
}

func (x *GetUserCriteriaResponse) GetEntries() []*UserCriterionEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type GetProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProgressRequest) Reset() {
	*x = GetProgressRequest{}
	mi := &file_api_health_health_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProgressRequest) ProtoMessage() {}

func (x *GetProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_health_health_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProgressRequest.ProtoReflect.Descriptor instead.
func (*GetProgressRequest) Descriptor() ([]byte, []int) {
	return file_api_health_health_proto_rawDescGZIP(), []int{13}
}

func (x *GetProgressRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetProgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Filled        int32                  `protobuf:"varint,2,opt,name=filled,proto3" json:"filled,omitempty"`
	Percent       float64                `protobuf:"fixed64,3,opt,name=percent,proto3" json:"percent,omitempty"`
	LevelLabel    string                 `protobuf:"bytes,4,opt,name=level_label,json=levelLabel,proto3" json:"level_label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProgressResponse) Reset() {
	*x = GetProgressResponse{}
	mi := &file_api_health_health_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProgressResponse) ProtoMessage() {}

func (x *GetProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_health_health_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProgressResponse.ProtoReflect.Descriptor instead.
func (*GetProgressResponse) Descriptor() ([]byte, []int) {
	return file_api_health_health_proto_rawDescGZIP(), []int{14}
}

func (x *GetProgressResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetProgressResponse) GetFilled() int32 {
	if x != nil {
		return x.Filled
	}
	return 0
}

func (x *GetProgressResponse) GetPercent() float64 {
	if x != nil {
		return x.Percent
	}
	return 0
}

func (x *GetProgressResponse) GetLevelLabel() string {
	if x != nil {
		return x.LevelLabel
	}
	return ""
}

// Set user_id and user_sex (optional) in the first message. Every message may carry filename and chunk: concatenate by filename in order, one PDF is expected per stream; user_id is required to store pending state.
type ImportCriteriaFromPdfRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Chunk         []byte                 `protobuf:"bytes,2,opt,name=chunk,proto3" json:"chunk,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserSex       string                 `protobuf:"bytes,4,opt,name=user_sex,json=userSex,proto3" json:"user_sex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportCriteriaFromPdfRequest) Reset() {
	*x = ImportCriteriaFromPdfRequest{}
	mi := &file_api_health_health_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportCriteriaFromPdfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportCriteriaFromPdfRequest) ProtoMessage() {}

func (x *ImportCriteriaFromPdfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_health_health_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportCriteriaFromPdfRequest.ProtoReflect.Descriptor instead.
func (*ImportCriteriaFromPdfRequest) Descriptor() ([]byte, []int) {
	return file_api_health_health_proto_rawDescGZIP(), []int{15}
}

func (x *ImportCriteriaFromPdfRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ImportCriteriaFromPdfRequest) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *ImportCriteriaFromPdfRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ImportCriteriaFromPdfRequest) GetUserSex() string {
	if x != nil {
		return x.UserSex
	}
	return ""
}

// Matched catalog criterion + value extracted from the document (same ids as ListCriteria / SetUserCriterion).
type ImportedUserCriterion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CriterionId   string                 `protobuf:"bytes,1,opt,name=criterion_id,json=criterionId,proto3" json:"criterion_id,omitempty"`
	CriterionName string                 `protobuf:"bytes,2,opt,name=criterion_name,json=criterionName,proto3" json:"criterion_name,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	InputType     string                 `protobuf:"bytes,4,opt,name=input_type,json=inputType,proto3" json:"input_type,omitempty"`    // "numeric", "check", "boolean" — from our criterion definition
	MeasuredAt    string                 `protobuf:"bytes,5,opt,name=measured_at,json=measuredAt,proto3" json:"measured_at,omitempty"` // optional ISO 8601 date if derivable from the document
	Instruction   string                 `protobuf:"bytes,6,opt,name=instruction,proto3" json:"instruction,omitempty"`                 // from catalog (where to obtain this criterion)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportedUserCriterion) Reset() {
	*x = ImportedUserCriterion{}
	mi := &file_api_health_health_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportedUserCriterion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportedUserCriterion) ProtoMessage() {}

func (x *ImportedUserCriterion) ProtoReflect() protoreflect.Message {
	mi := &file_api_health_health_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportedUserCriterion.ProtoReflect.Descriptor instead.
func (*ImportedUserCriterion) Descriptor() ([]byte, []int) {
	return file_api_health_health_proto_rawDescGZIP(), []int{16}
}

func (x *ImportedUserCriterion) GetCriterionId() string {
	if x != nil {
		return x.CriterionId
	}
	return ""
}

func (x *ImportedUserCriterion) GetCriterionName() string {
	if x != nil {
		return x.CriterionName
	}
	return ""
}

func (x *ImportedUserCriterion) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ImportedUserCriterion) GetInputType() string {
	if x != nil {
		return x.InputType
	}
	return ""
}

func (x *ImportedUserCriterion) GetMeasuredAt() string {
	if x != nil {
		return x.MeasuredAt
	}
	return ""
}

func (x *ImportedUserCriterion) GetInstruction() string {
	if x != nil {
		return x.Instruction
	}
	return ""
}

type ImportCriteriaFromPdfResponse struct {
	state        protoimpl.MessageState   `protogen:"open.v1"`
	UserCriteria []*ImportedUserCriterion `protobuf:"bytes,1,rep,name=user_criteria,json=userCriteria,proto3" json:"user_criteria,omitempty"`
	// Staging id for ConfirmPendingImport; empty if no suggestions.
	PendingImportId string `protobuf:"bytes,2,opt,name=pending_import_id,json=pendingImportId,proto3" json:"pending_import_id,omitempty"`
	ModelNote       string `protobuf:"bytes,3,opt,name=model_note,json=modelNote,proto3" json:"model_note,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ImportCriteriaFromPdfResponse) Reset() {
	*x = ImportCriteriaFromPdfResponse{}
	mi := &file_api_health_health_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportCriteriaFromPdfResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportCriteriaFromPdfResponse) ProtoMessage() {}

func (x *ImportCriteriaFromPdfResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_health_health_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportCriteriaFromPdfResponse.ProtoReflect.Descriptor instead.
func (*ImportCriteriaFromPdfResponse) Descriptor() ([]byte, []int) {
	return file_api_health_health_proto_rawDescGZIP(), []int{17}
}

func (x *ImportCriteriaFromPdfResponse) GetUserCriteria() []*ImportedUserCriterion {
	if x != nil {
		return x.UserCriteria
	}
	return nil
}

func (x *ImportCriteriaFromPdfResponse) GetPendingImportId() string {
	if x != nil {
		return x.PendingImportId
	}
	return ""
}

func (x *ImportCriteriaFromPdfResponse) GetModelNote() string {
	if x != nil {
		return x.ModelNote
	}
	return ""
}

type ConfirmPendingImportRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	UserId    string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PendingId string                 `protobuf:"bytes,2,opt,name=pending_id,json=pendingId,proto3" json:"pending_id,omitempty"`
	// true: write to user_criteria; false: only delete from Redis
	Accept        bool   `protobuf:"varint,3,opt,name=accept,proto3" json:"accept,omitempty"`
	UserSex       string `protobuf:"bytes,4,opt,name=user_sex,json=userSex,proto3" json:"user_sex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmPendingImportRequest) Reset() {
	*x = ConfirmPendingImportRequest{}
	mi := &file_api_health_health_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmPendingImportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmPendingImportRequest) ProtoMessage() {}

func (x *ConfirmPendingImportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_health_health_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmPendingImportRequest.ProtoReflect.Descriptor instead.
func (*ConfirmPendingImportRequest) Descriptor() ([]byte, []int) {
	return file_api_health_health_proto_rawDescGZIP(), []int{18}
}

func (x *ConfirmPendingImportRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ConfirmPendingImportRequest) GetPendingId() string {
	if x != nil {
		return x.PendingId
	}
	return ""
}

func (x *ConfirmPendingImportRequest) GetAccept() bool {
	if x != nil {
		return x.Accept
	}
	return false
}

func (x *ConfirmPendingImportRequest) GetUserSex() string {
	if x != nil {
		return x.UserSex
	}
	return ""
}

type ConfirmPendingImportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Applied       int32                  `protobuf:"varint,1,opt,name=applied,proto3" json:"applied,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmPendingImportResponse) Reset() {
	*x = ConfirmPendingImportResponse{}
	mi := &file_api_health_health_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmPendingImportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmPendingImportResponse) ProtoMessage() {}

func (x *ConfirmPendingImportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_health_health_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmPendingImportResponse.ProtoReflect.Descriptor instead.
func (*ConfirmPendingImportResponse) Descriptor() ([]byte, []int) {
	return file_api_health_health_proto_rawDescGZIP(), []int{19}
}

func (x *ConfirmPendingImportResponse) GetApplied() int32 {
	if x != nil {
		return x.Applied
	}
	return 0
}

func (x *ConfirmPendingImportResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfirmPendingImportResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type Recommendation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CriterionId   string                 `protobuf:"bytes,1,opt,name=criterion_id,json=criterionId,proto3" json:"criterion_id,omitempty"`
	CriterionName string                 `protobuf:"bytes,2,opt,name=criterion_name,json=criterionName,proto3" json:"criterion_name,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Severity      string                 `protobuf:"bytes,4,opt,name=severity,proto3" json:"severity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Recommendation) Reset() {
	*x = Recommendation{}
	mi := &file_api_health_health_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Recommendation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Recommendation) ProtoMessage() {}

func (x *Recommendation) ProtoReflect() protoreflect.Message {
	mi := &file_api_health_health_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Recommendation.ProtoReflect.Descriptor instead.
func (*Recommendation) Descriptor() ([]byte, []int) {
	return file_api_health_health_proto_rawDescGZIP(), []int{20}
}

func (x *Recommendation) GetCriterionId() string {
	if x != nil {
		return x.CriterionId
	}
	return ""
}

func (x *Recommendation) GetCriterionName() string {
	if x != nil {
		return x.CriterionName
	}
	return ""
}

func (x *Recommendation) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Recommendation) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

type GetRecommendationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserSex       string                 `protobuf:"bytes,2,opt,name=user_sex,json=userSex,proto3" json:"user_sex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecommendationsRequest) Reset() {
	*x = GetRecommendationsRequest{}
	mi := &file_api_health_health_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendationsRequest) ProtoMessage() {}

func (x *GetRecommendationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_health_health_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendationsRequest.ProtoReflect.Descriptor instead.
func (*GetRecommendationsRequest) Descriptor() ([]byte, []int) {
	return file_api_health_health_proto_rawDescGZIP(), []int{21}
}

func (x *GetRecommendationsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetRecommendationsRequest) GetUserSex() string {
	if x != nil {
		return x.UserSex
	}
	return ""
}

type GetRecommendationsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Recommendations []*Recommendation      `protobuf:"bytes,1,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetRecommendationsResponse) Reset() {
	*x = GetRecommendationsResponse{}
	mi := &file_api_health_health_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendationsResponse) ProtoMessage() {}

func (x *GetRecommendationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_health_health_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendationsResponse.ProtoReflect.Descriptor instead.
func (*GetRecommendationsResponse) Descriptor() ([]byte, []int) {
	return file_api_health_health_proto_rawDescGZIP(), []int{22}
}

func (x *GetRecommendationsResponse) GetRecommendations() []*Recommendation {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

// WeeklyRecommendationItem is one entry in a user's weekly plan.
type WeeklyRecommendationItem struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RecommendationId string                 `protobuf:"bytes,1,opt,name=recommendation_id,json=recommendationId,proto3" json:"recommendation_id,omitempty"`
	CriterionId      string                 `protobuf:"bytes,2,opt,name=criterion_id,json=criterionId,proto3" json:"criterion_id,omitempty"`
	CriterionName    string                 `protobuf:"bytes,3,opt,name=criterion_name,json=criterionName,proto3" json:"criterion_name,omitempty"`
	Type             string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Title            string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Weight           int32                  `protobuf:"varint,6,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WeeklyRecommendationItem) Reset() {
	*x = WeeklyRecommendationItem{}
	mi := &file_api_health_health_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeeklyRecommendationItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeeklyRecommendationItem) ProtoMessage() {}

func (x *WeeklyRecommendationItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_health_health_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeeklyRecommendationItem.ProtoReflect.Descriptor instead.
func (*WeeklyRecommendationItem) Descriptor() ([]byte, []int) {
	return file_api_health_health_proto_rawDescGZIP(), []int{23}
}

func (x *WeeklyRecommendationItem) GetRecommendationId() string {
	if x != nil {
		return x.RecommendationId
	}
	return ""
}

func (x *WeeklyRecommendationItem) GetCriterionId() string {
	if x != nil {
		return x.CriterionId
	}
	return ""
}

func (x *WeeklyRecommendationItem) GetCriterionName() string {
	if x != nil {
		return x.CriterionName
	}
	return ""
}

func (x *WeeklyRecommendationItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *WeeklyRecommendationItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *WeeklyRecommendationItem) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type GetWeeklyRecommendationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWeeklyRecommendationsRequest) Reset() {
	*x = GetWeeklyRecommendationsRequest{}
	mi := &file_api_health_health_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWeeklyRecommendationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeeklyRecommendationsRequest) ProtoMessage() {}

func (x *GetWeeklyRecommendationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_health_health_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeeklyRecommendationsRequest.ProtoReflect.Descriptor instead.
func (*GetWeeklyRecommendationsRequest) Descriptor() ([]byte, []int) {
	return file_api_health_health_proto_rawDescGZIP(), []int{24}
}

func (x *GetWeeklyRecommendationsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetWeeklyRecommendationsResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Items         []*WeeklyRecommendationItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	WeekStart     string                      `protobuf:"bytes,2,opt,name=week_start,json=weekStart,proto3" json:"week_start,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWeeklyRecommendationsResponse) Reset() {
	*x = GetWeeklyRecommendationsResponse{}
	mi := &file_api_health_health_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWeeklyRecommendationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeeklyRecommendationsResponse) ProtoMessage() {}

func (x *GetWeeklyRecommendationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_health_health_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeeklyRecommendationsResponse.ProtoReflect.Descriptor instead.
func (*GetWeeklyRecommendationsResponse) Descriptor() ([]byte, []int) {
	return file_api_health_health_proto_rawDescGZIP(), []int{25}
}

func (x *GetWeeklyRecommendationsResponse) GetItems() []*WeeklyRecommendationItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetWeeklyRecommendationsResponse) GetWeekStart() string {
	if x != nil {
		return x.WeekStart
	}
	return ""
}

type SendNotificationRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Channel          string                 `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	NotificationType string                 `protobuf:"bytes,3,opt,name=notification_type,json=notificationType,proto3" json:"notification_type,omitempty"`
	TemplateCode     string                 `protobuf:"bytes,4,opt,name=template_code,json=templateCode,proto3" json:"template_code,omitempty"`
	PayloadJson      string                 `protobuf:"bytes,5,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SendNotificationRequest) Reset() {
	*x = SendNotificationRequest{}
	mi := &file_api_health_health_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationRequest) ProtoMessage() {}

func (x *SendNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_health_health_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationRequest.ProtoReflect.Descriptor instead.
func (*SendNotificationRequest) Descriptor() ([]byte, []int) {
	return file_api_health_health_proto_rawDescGZIP(), []int{26}
}

func (x *SendNotificationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SendNotificationRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *SendNotificationRequest) GetNotificationType() string {
	if x != nil {
		return x.NotificationType
	}
	return ""
}

func (x *SendNotificationRequest) GetTemplateCode() string {
	if x != nil {
		return x.TemplateCode
	}
	return ""
}

func (x *SendNotificationRequest) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

type SendNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNotificationResponse) Reset() {
	*x = SendNotificationResponse{}
	mi := &file_api_health_health_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationResponse) ProtoMessage() {}

func (x *SendNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_health_health_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationResponse.ProtoReflect.Descriptor instead.
func (*SendNotificationResponse) Descriptor() ([]byte, []int) {
	return file_api_health_health_proto_rawDescGZIP(), []int{27}
}

type AdminRecommendation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CriterionId   string                 `protobuf:"bytes,2,opt,name=criterion_id,json=criterionId,proto3" json:"criterion_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Texts         []string               `protobuf:"bytes,5,rep,name=texts,proto3" json:"texts,omitempty"`
	BaseWeight    int32                  `protobuf:"varint,6,opt,name=base_weight,json=baseWeight,proto3" json:"base_weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminRecommendation) Reset() {
	*x = AdminRecommendation{}
	mi := &file_api_health_health_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminRecommendation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminRecommendation) ProtoMessage() {}

func (x *AdminRecommendation) ProtoReflect() protoreflect.Message {
	mi := &file_api_health_health_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminRecommendation.ProtoReflect.Descriptor instead.
func (*AdminRecommendation) Descriptor() ([]byte, []int) {
	return file_api_health_health_proto_rawDescGZIP(), []int{28}
}

func (x *AdminRecommendation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AdminRecommendation) GetCriterionId() string {
	if x != nil {
		return x.CriterionId
	}
	return ""
}

func (x *AdminRecommendation) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AdminRecommendation) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AdminRecommendation) GetTexts() []string {
	if x != nil {
		return x.Texts
	}
	return nil
}

func (x *AdminRecommendation) GetBaseWeight() int32 {
	if x != nil {
		return x.BaseWeight
	}
	return 0
}

type AdminListRecommendationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CriterionId   string                 `protobuf:"bytes,1,opt,name=criterion_id,json=criterionId,proto3" json:"criterion_id,omitempty"` // empty = all
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminListRecommendationsRequest) Reset() {
	*x = AdminListRecommendationsRequest{}
	mi := &file_api_health_health_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListRecommendationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListRecommendationsRequest) ProtoMessage() {}

func (x *AdminListRecommendationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_health_health_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListRecommendationsRequest.ProtoReflect.Descriptor instead.
func (*AdminListRecommendationsRequest) Descriptor() ([]byte, []int) {
	return file_api_health_health_proto_rawDescGZIP(), []int{29}
}

func (x *AdminListRecommendationsRequest) GetCriterionId() string {
	if x != nil {
		return x.CriterionId
	}
	return ""
}

type AdminListRecommendationsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Recommendations []*AdminRecommendation `protobuf:"bytes,1,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AdminListRecommendationsResponse) Reset() {
	*x = AdminListRecommendationsResponse{}
	mi := &file_api_health_health_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminListRecommendationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminListRecommendationsResponse) ProtoMessage() {}

func (x *AdminListRecommendationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_health_health_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminListRecommendationsResponse.ProtoReflect.Descriptor instead.
func (*AdminListRecommendationsResponse) Descriptor() ([]byte, []int) {
	return file_api_health_health_proto_rawDescGZIP(), []int{30}
}

func (x *AdminListRecommendationsResponse) GetRecommendations() []*AdminRecommendation {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

type AdminUpsertRecommendationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Recommendation *AdminRecommendation   `protobuf:"bytes,1,opt,name=recommendation,proto3" json:"recommendation,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AdminUpsertRecommendationRequest) Reset() {
	*x = AdminUpsertRecommendationRequest{}
	mi := &file_api_health_health_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUpsertRecommendationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUpsertRecommendationRequest) ProtoMessage() {}

func (x *AdminUpsertRecommendationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_health_health_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUpsertRecommendationRequest.ProtoReflect.Descriptor instead.
func (*AdminUpsertRecommendationRequest) Descriptor() ([]byte, []int) {
	return file_api_health_health_proto_rawDescGZIP(), []int{31}
}

func (x *AdminUpsertRecommendationRequest) GetRecommendation() *AdminRecommendation {
	if x != nil {
		return x.Recommendation
	}
	return nil
}

type AdminUpsertRecommendationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Recommendation *AdminRecommendation   `protobuf:"bytes,1,opt,name=recommendation,proto3" json:"recommendation,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AdminUpsertRecommendationResponse) Reset() {
	*x = AdminUpsertRecommendationResponse{}
	mi := &file_api_health_health_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUpsertRecommendationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUpsertRecommendationResponse) ProtoMessage() {}

func (x *AdminUpsertRecommendationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_health_health_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUpsertRecommendationResponse.ProtoReflect.Descriptor instead.
func (*AdminUpsertRecommendationResponse) Descriptor() ([]byte, []int) {
	return file_api_health_health_proto_rawDescGZIP(), []int{32}
}

func (x *AdminUpsertRecommendationResponse) GetRecommendation() *AdminRecommendation {
	if x != nil {
		return x.Recommendation
	}
	return nil
}

type AdminDeleteRecommendationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminDeleteRecommendationRequest) Reset() {
	*x = AdminDeleteRecommendationRequest{}
	mi := &file_api_health_health_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminDeleteRecommendationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminDeleteRecommendationRequest) ProtoMessage() {}

func (x *AdminDeleteRecommendationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_health_health_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminDeleteRecommendationRequest.ProtoReflect.Descriptor instead.
func (*AdminDeleteRecommendationRequest) Descriptor() ([]byte, []int) {
	return file_api_health_health_proto_rawDescGZIP(), []int{33}
}

func (x *AdminDeleteRecommendationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AdminDeleteRecommendationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminDeleteRecommendationResponse) Reset() {
	*x = AdminDeleteRecommendationResponse{}
	mi := &file_api_health_health_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminDeleteRecommendationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminDeleteRecommendationResponse) ProtoMessage() {}

func (x *AdminDeleteRecommendationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_health_health_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminDeleteRecommendationResponse.ProtoReflect.Descriptor instead.
func (*AdminDeleteRecommendationResponse) Descriptor() ([]byte, []int) {
	return file_api_health_health_proto_rawDescGZIP(), []int{34}
}

func (x *AdminDeleteRecommendationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type AdminUpsertCriterionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Criterion     *Criterion             `protobuf:"bytes,1,opt,name=criterion,proto3" json:"criterion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUpsertCriterionRequest) Reset() {
	*x = AdminUpsertCriterionRequest{}
	mi := &file_api_health_health_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUpsertCriterionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUpsertCriterionRequest) ProtoMessage() {}

func (x *AdminUpsertCriterionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_health_health_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUpsertCriterionRequest.ProtoReflect.Descriptor instead.
func (*AdminUpsertCriterionRequest) Descriptor() ([]byte, []int) {
	return file_api_health_health_proto_rawDescGZIP(), []int{35}
}

func (x *AdminUpsertCriterionRequest) GetCriterion() *Criterion {
	if x != nil {
		return x.Criterion
	}
	return nil
}

type AdminUpsertCriterionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Criterion     *Criterion             `protobuf:"bytes,1,opt,name=criterion,proto3" json:"criterion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUpsertCriterionResponse) Reset() {
	*x = AdminUpsertCriterionResponse{}
	mi := &file_api_health_health_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUpsertCriterionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUpsertCriterionResponse) ProtoMessage() {}

func (x *AdminUpsertCriterionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_health_health_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUpsertCriterionResponse.ProtoReflect.Descriptor instead.
func (*AdminUpsertCriterionResponse) Descriptor() ([]byte, []int) {
	return file_api_health_health_proto_rawDescGZIP(), []int{36}
}

func (x *AdminUpsertCriterionResponse) GetCriterion() *Criterion {
	if x != nil {
		return x.Criterion
	}
	return nil
}

var File_api_health_health_proto protoreflect.FileDescriptor

const file_api_health_health_proto_rawDesc = "" +
	"\n" +
	"\x17api/health/health.proto\x12\x06health\"S\n" +
	"\x0eCriterionGroup\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x03 \x01(\x05R\tsortOrder\"\x13\n" +
	"\x11ListGroupsRequest\"D\n" +
	"\x12ListGroupsResponse\x12.\n" +
	"\x06groups\x18\x01 \x03(\v2\x16.health.CriterionGroupR\x06groups\"\xf3\x02\n" +
	"\tCriterion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\x12\x10\n" +
	"\x03sex\x18\x04 \x01(\tR\x03sex\x12\x1d\n" +
	"\n" +
	"input_type\x18\x06 \x01(\tR\tinputType\x12\x1a\n" +
	"\blifetime\x18\a \x01(\x05R\blifetime\x12\x19\n" +
	"\bgroup_id\x18\b \x01(\tR\agroupId\x12\x1d\n" +
	"\n" +
	"sort_order\x18\t \x01(\x05R\tsortOrder\x12 \n" +
	"\tmin_value\x18\n" +
	" \x01(\x01H\x00R\bminValue\x88\x01\x01\x12 \n" +
	"\tmax_value\x18\v \x01(\x01H\x01R\bmaxValue\x88\x01\x01\x12\x19\n" +
	"\x05delta\x18\f \x01(\x01H\x02R\x05delta\x88\x01\x01\x12 \n" +
	"\vinstruction\x18\r \x01(\tR\vinstructionB\f\n" +
	"\n" +
	"_min_valueB\f\n" +
	"\n" +
	"_max_valueB\b\n" +
	"\x06_delta\"I\n" +
	"\x13ListCriteriaRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\buser_sex\x18\x02 \x01(\tR\auserSex\"E\n" +
	"\x14ListCriteriaResponse\x12-\n" +
	"\bcriteria\x18\x01 \x03(\v2\x11.health.CriterionR\bcriteria\"\xbf\x01\n" +
	"\x17SetUserCriterionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fcriterion_id\x18\x02 \x01(\tR\vcriterionId\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x1f\n" +
	"\vmeasured_at\x18\x05 \x01(\tR\n" +
	"measuredAt\x12\x19\n" +
	"\buser_sex\x18\x06 \x01(\tR\auserSex\"f\n" +
	"\x18SetUserCriterionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x120\n" +
	"\x05entry\x18\x02 \x01(\v2\x1a.health.UserCriterionEntryR\x05entry\"/\n" +
	"\x14ResetCriteriaRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"1\n" +
	"\x15ResetCriteriaResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xc2\x02\n" +
	"\x12UserCriterionEntry\x12!\n" +
	"\fcriterion_id\x18\x01 \x01(\tR\vcriterionId\x12%\n" +
	"\x0ecriterion_name\x18\x02 \x01(\tR\rcriterionName\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12&\n" +
	"\x0erecommendation\x18\x05 \x01(\tR\x0erecommendation\x12\x14\n" +
	"\x05level\x18\x06 \x01(\x05R\x05level\x12\x1a\n" +
	"\bseverity\x18\a \x01(\tR\bseverity\x12\x1d\n" +
	"\n" +
	"input_type\x18\b \x01(\tR\tinputType\x12\x19\n" +
	"\bgroup_id\x18\t \x01(\tR\agroupId\x12 \n" +
	"\vinstruction\x18\n" +
	" \x01(\tR\vinstruction\"L\n" +
	"\x16GetUserCriteriaRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\buser_sex\x18\x02 \x01(\tR\auserSex\"O\n" +
	"\x17GetUserCriteriaResponse\x124\n" +
	"\aentries\x18\x01 \x03(\v2\x1a.health.UserCriterionEntryR\aentries\"-\n" +
	"\x12GetProgressRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"~\n" +
	"\x13GetProgressResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x16\n" +
	"\x06filled\x18\x02 \x01(\x05R\x06filled\x12\x18\n" +
	"\apercent\x18\x03 \x01(\x01R\apercent\x12\x1f\n" +
	"\vlevel_label\x18\x04 \x01(\tR\n" +
	"levelLabel\"\x84\x01\n" +
	"\x1cImportCriteriaFromPdfRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x14\n" +
	"\x05chunk\x18\x02 \x01(\fR\x05chunk\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x19\n" +
	"\buser_sex\x18\x04 \x01(\tR\auserSex\"\xd9\x01\n" +
	"\x15ImportedUserCriterion\x12!\n" +
	"\fcriterion_id\x18\x01 \x01(\tR\vcriterionId\x12%\n" +
	"\x0ecriterion_name\x18\x02 \x01(\tR\rcriterionName\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x1d\n" +
	"\n" +
	"input_type\x18\x04 \x01(\tR\tinputType\x12\x1f\n" +
	"\vmeasured_at\x18\x05 \x01(\tR\n" +
	"measuredAt\x12 \n" +
	"\vinstruction\x18\x06 \x01(\tR\vinstruction\"\xae\x01\n" +
	"\x1dImportCriteriaFromPdfResponse\x12B\n" +
	"\ruser_criteria\x18\x01 \x03(\v2\x1d.health.ImportedUserCriterionR\fuserCriteria\x12*\n" +
	"\x11pending_import_id\x18\x02 \x01(\tR\x0fpendingImportId\x12\x1d\n" +
	"\n" +
	"model_note\x18\x03 \x01(\tR\tmodelNote\"\x88\x01\n" +
	"\x1bConfirmPendingImportRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"pending_id\x18\x02 \x01(\tR\tpendingId\x12\x16\n" +
	"\x06accept\x18\x03 \x01(\bR\x06accept\x12\x19\n" +
	"\buser_sex\x18\x04 \x01(\tR\auserSex\"w\n" +
	"\x1cConfirmPendingImportResponse\x12\x18\n" +
	"\aapplied\x18\x01 \x01(\x05R\aapplied\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\x8a\x01\n" +
	"\x0eRecommendation\x12!\n" +
	"\fcriterion_id\x18\x01 \x01(\tR\vcriterionId\x12%\n" +
	"\x0ecriterion_name\x18\x02 \x01(\tR\rcriterionName\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x1a\n" +
	"\bseverity\x18\x04 \x01(\tR\bseverity\"O\n" +
	"\x19GetRecommendationsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\buser_sex\x18\x02 \x01(\tR\auserSex\"^\n" +
	"\x1aGetRecommendationsResponse\x12@\n" +
	"\x0frecommendations\x18\x01 \x03(\v2\x16.health.RecommendationR\x0frecommendations\"\xd3\x01\n" +
	"\x18WeeklyRecommendationItem\x12+\n" +
	"\x11recommendation_id\x18\x01 \x01(\tR\x10recommendationId\x12!\n" +
	"\fcriterion_id\x18\x02 \x01(\tR\vcriterionId\x12%\n" +
	"\x0ecriterion_name\x18\x03 \x01(\tR\rcriterionName\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x16\n" +
	"\x06weight\x18\x06 \x01(\x05R\x06weight\":\n" +
	"\x1fGetWeeklyRecommendationsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"y\n" +
	" GetWeeklyRecommendationsResponse\x126\n" +
	"\x05items\x18\x01 \x03(\v2 .health.WeeklyRecommendationItemR\x05items\x12\x1d\n" +
	"\n" +
	"week_start\x18\x02 \x01(\tR\tweekStart\"\xc1\x01\n" +
	"\x17SendNotificationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\achannel\x18\x02 \x01(\tR\achannel\x12+\n" +
	"\x11notification_type\x18\x03 \x01(\tR\x10notificationType\x12#\n" +
	"\rtemplate_code\x18\x04 \x01(\tR\ftemplateCode\x12!\n" +
	"\fpayload_json\x18\x05 \x01(\tR\vpayloadJson\"\x1a\n" +
	"\x18SendNotificationResponse\"\xa9\x01\n" +
	"\x13AdminRecommendation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fcriterion_id\x18\x02 \x01(\tR\vcriterionId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x14\n" +
	"\x05texts\x18\x05 \x03(\tR\x05texts\x12\x1f\n" +
	"\vbase_weight\x18\x06 \x01(\x05R\n" +
	"baseWeight\"D\n" +
	"\x1fAdminListRecommendationsRequest\x12!\n" +
	"\fcriterion_id\x18\x01 \x01(\tR\vcriterionId\"i\n" +
	" AdminListRecommendationsResponse\x12E\n" +
	"\x0frecommendations\x18\x01 \x03(\v2\x1b.health.AdminRecommendationR\x0frecommendations\"g\n" +
	" AdminUpsertRecommendationRequest\x12C\n" +
	"\x0erecommendation\x18\x01 \x01(\v2\x1b.health.AdminRecommendationR\x0erecommendation\"h\n" +
	"!AdminUpsertRecommendationResponse\x12C\n" +
	"\x0erecommendation\x18\x01 \x01(\v2\x1b.health.AdminRecommendationR\x0erecommendation\"2\n" +
	" AdminDeleteRecommendationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"=\n" +
	"!AdminDeleteRecommendationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"N\n" +
	"\x1bAdminUpsertCriterionRequest\x12/\n" +
	"\tcriterion\x18\x01 \x01(\v2\x11.health.CriterionR\tcriterion\"O\n" +
	"\x1cAdminUpsertCriterionResponse\x12/\n" +
	"\tcriterion\x18\x01 \x01(\v2\x11.health.CriterionR\tcriterion2\x84\v\n" +
	"\rHealthService\x12C\n" +
	"\n" +
	"ListGroups\x12\x19.health.ListGroupsRequest\x1a\x1a.health.ListGroupsResponse\x12I\n" +
	"\fListCriteria\x12\x1b.health.ListCriteriaRequest\x1a\x1c.health.ListCriteriaResponse\x12U\n" +
	"\x10SetUserCriterion\x12\x1f.health.SetUserCriterionRequest\x1a .health.SetUserCriterionResponse\x12L\n" +
	"\rResetCriteria\x12\x1c.health.ResetCriteriaRequest\x1a\x1d.health.ResetCriteriaResponse\x12R\n" +
	"\x0fGetUserCriteria\x12\x1e.health.GetUserCriteriaRequest\x1a\x1f.health.GetUserCriteriaResponse\x12F\n" +
	"\vGetProgress\x12\x1a.health.GetProgressRequest\x1a\x1b.health.GetProgressResponse\x12f\n" +
	"\x15ImportCriteriaFromPdf\x12$.health.ImportCriteriaFromPdfRequest\x1a%.health.ImportCriteriaFromPdfResponse(\x01\x12a\n" +
	"\x14ConfirmPendingImport\x12#.health.ConfirmPendingImportRequest\x1a$.health.ConfirmPendingImportResponse\x12[\n" +
	"\x12GetRecommendations\x12!.health.GetRecommendationsRequest\x1a\".health.GetRecommendationsResponse\x12m\n" +
	"\x18GetWeeklyRecommendations\x12'.health.GetWeeklyRecommendationsRequest\x1a(.health.GetWeeklyRecommendationsResponse\x12U\n" +
	"\x10SendNotification\x12\x1f.health.SendNotificationRequest\x1a .health.SendNotificationResponse\x12m\n" +
	"\x18AdminListRecommendations\x12'.health.AdminListRecommendationsRequest\x1a(.health.AdminListRecommendationsResponse\x12p\n" +
	"\x19AdminUpsertRecommendation\x12(.health.AdminUpsertRecommendationRequest\x1a).health.AdminUpsertRecommendationResponse\x12p\n" +
	"\x19AdminDeleteRecommendation\x12(.health.AdminDeleteRecommendationRequest\x1a).health.AdminDeleteRecommendationResponse\x12a\n" +
	"\x14AdminUpsertCriterion\x12#.health.AdminUpsertCriterionRequest\x1a$.health.AdminUpsertCriterionResponseB3Z1github.com/helthtech/core-health/pkg/proto/healthb\x06proto3"

var (
	file_api_health_health_proto_rawDescOnce sync.Once
	file_api_health_health_proto_rawDescData []byte
)

func file_api_health_health_proto_rawDescGZIP() []byte {
	file_api_health_health_proto_rawDescOnce.Do(func() {
		file_api_health_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_health_health_proto_rawDesc), len(file_api_health_health_proto_rawDesc)))
	})
	return file_api_health_health_proto_rawDescData
}

var file_api_health_health_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_api_health_health_proto_goTypes = []any{
	(*CriterionGroup)(nil),                    // 0: health.CriterionGroup
	(*ListGroupsRequest)(nil),                 // 1: health.ListGroupsRequest
	(*ListGroupsResponse)(nil),                // 2: health.ListGroupsResponse
	(*Criterion)(nil),                         // 3: health.Criterion
	(*ListCriteriaRequest)(nil),               // 4: health.ListCriteriaRequest
	(*ListCriteriaResponse)(nil),              // 5: health.ListCriteriaResponse
	(*SetUserCriterionRequest)(nil),           // 6: health.SetUserCriterionRequest
	(*SetUserCriterionResponse)(nil),          // 7: health.SetUserCriterionResponse
	(*ResetCriteriaRequest)(nil),              // 8: health.ResetCriteriaRequest
	(*ResetCriteriaResponse)(nil),             // 9: health.ResetCriteriaResponse
	(*UserCriterionEntry)(nil),                // 10: health.UserCriterionEntry
	(*GetUserCriteriaRequest)(nil),            // 11: health.GetUserCriteriaRequest
	(*GetUserCriteriaResponse)(nil),           // 12: health.GetUserCriteriaResponse
	(*GetProgressRequest)(nil),                // 13: health.GetProgressRequest
	(*GetProgressResponse)(nil),               // 14: health.GetProgressResponse
	(*ImportCriteriaFromPdfRequest)(nil),      // 15: health.ImportCriteriaFromPdfRequest
	(*ImportedUserCriterion)(nil),             // 16: health.ImportedUserCriterion
	(*ImportCriteriaFromPdfResponse)(nil),     // 17: health.ImportCriteriaFromPdfResponse
	(*ConfirmPendingImportRequest)(nil),       // 18: health.ConfirmPendingImportRequest
	(*ConfirmPendingImportResponse)(nil),      // 19: health.ConfirmPendingImportResponse
	(*Recommendation)(nil),                    // 20: health.Recommendation
	(*GetRecommendationsRequest)(nil),         // 21: health.GetRecommendationsRequest
	(*GetRecommendationsResponse)(nil),        // 22: health.GetRecommendationsResponse
	(*WeeklyRecommendationItem)(nil),          // 23: health.WeeklyRecommendationItem
	(*GetWeeklyRecommendationsRequest)(nil),   // 24: health.GetWeeklyRecommendationsRequest
	(*GetWeeklyRecommendationsResponse)(nil),  // 25: health.GetWeeklyRecommendationsResponse
	(*SendNotificationRequest)(nil),           // 26: health.SendNotificationRequest
	(*SendNotificationResponse)(nil),          // 27: health.SendNotificationResponse
	(*AdminRecommendation)(nil),               // 28: health.AdminRecommendation
	(*AdminListRecommendationsRequest)(nil),   // 29: health.AdminListRecommendationsRequest
	(*AdminListRecommendationsResponse)(nil),  // 30: health.AdminListRecommendationsResponse
	(*AdminUpsertRecommendationRequest)(nil),  // 31: health.AdminUpsertRecommendationRequest
	(*AdminUpsertRecommendationResponse)(nil), // 32: health.AdminUpsertRecommendationResponse
	(*AdminDeleteRecommendationRequest)(nil),  // 33: health.AdminDeleteRecommendationRequest
	(*AdminDeleteRecommendationResponse)(nil), // 34: health.AdminDeleteRecommendationResponse
	(*AdminUpsertCriterionRequest)(nil),       // 35: health.AdminUpsertCriterionRequest
	(*AdminUpsertCriterionResponse)(nil),      // 36: health.AdminUpsertCriterionResponse
}
var file_api_health_health_proto_depIdxs = []int32{
	0,  // 0: health.ListGroupsResponse.groups:type_name -> health.CriterionGroup
	3,  // 1: health.ListCriteriaResponse.criteria:type_name -> health.Criterion
	10, // 2: health.SetUserCriterionResponse.entry:type_name -> health.UserCriterionEntry
	10, // 3: health.GetUserCriteriaResponse.entries:type_name -> health.UserCriterionEntry
	16, // 4: health.ImportCriteriaFromPdfResponse.user_criteria:type_name -> health.ImportedUserCriterion
	20, // 5: health.GetRecommendationsResponse.recommendations:type_name -> health.Recommendation
	23, // 6: health.GetWeeklyRecommendationsResponse.items:type_name -> health.WeeklyRecommendationItem
	28, // 7: health.AdminListRecommendationsResponse.recommendations:type_name -> health.AdminRecommendation
	28, // 8: health.AdminUpsertRecommendationRequest.recommendation:type_name -> health.AdminRecommendation
	28, // 9: health.AdminUpsertRecommendationResponse.recommendation:type_name -> health.AdminRecommendation
	3,  // 10: health.AdminUpsertCriterionRequest.criterion:type_name -> health.Criterion
	3,  // 11: health.AdminUpsertCriterionResponse.criterion:type_name -> health.Criterion
	1,  // 12: health.HealthService.ListGroups:input_type -> health.ListGroupsRequest
	4,  // 13: health.HealthService.ListCriteria:input_type -> health.ListCriteriaRequest
	6,  // 14: health.HealthService.SetUserCriterion:input_type -> health.SetUserCriterionRequest
	8,  // 15: health.HealthService.ResetCriteria:input_type -> health.ResetCriteriaRequest
	11, // 16: health.HealthService.GetUserCriteria:input_type -> health.GetUserCriteriaRequest
	13, // 17: health.HealthService.GetProgress:input_type -> health.GetProgressRequest
	15, // 18: health.HealthService.ImportCriteriaFromPdf:input_type -> health.ImportCriteriaFromPdfRequest
	18, // 19: health.HealthService.ConfirmPendingImport:input_type -> health.ConfirmPendingImportRequest
	21, // 20: health.HealthService.GetRecommendations:input_type -> health.GetRecommendationsRequest
	24, // 21: health.HealthService.GetWeeklyRecommendations:input_type -> health.GetWeeklyRecommendationsRequest
	26, // 22: health.HealthService.SendNotification:input_type -> health.SendNotificationRequest
	29, // 23: health.HealthService.AdminListRecommendations:input_type -> health.AdminListRecommendationsRequest
	31, // 24: health.HealthService.AdminUpsertRecommendation:input_type -> health.AdminUpsertRecommendationRequest
	33, // 25: health.HealthService.AdminDeleteRecommendation:input_type -> health.AdminDeleteRecommendationRequest
	35, // 26: health.HealthService.AdminUpsertCriterion:input_type -> health.AdminUpsertCriterionRequest
	2,  // 27: health.HealthService.ListGroups:output_type -> health.ListGroupsResponse
	5,  // 28: health.HealthService.ListCriteria:output_type -> health.ListCriteriaResponse
	7,  // 29: health.HealthService.SetUserCriterion:output_type -> health.SetUserCriterionResponse
	9,  // 30: health.HealthService.ResetCriteria:output_type -> health.ResetCriteriaResponse
	12, // 31: health.HealthService.GetUserCriteria:output_type -> health.GetUserCriteriaResponse
	14, // 32: health.HealthService.GetProgress:output_type -> health.GetProgressResponse
	17, // 33: health.HealthService.ImportCriteriaFromPdf:output_type -> health.ImportCriteriaFromPdfResponse
	19, // 34: health.HealthService.ConfirmPendingImport:output_type -> health.ConfirmPendingImportResponse
	22, // 35: health.HealthService.GetRecommendations:output_type -> health.GetRecommendationsResponse
	25, // 36: health.HealthService.GetWeeklyRecommendations:output_type -> health.GetWeeklyRecommendationsResponse
	27, // 37: health.HealthService.SendNotification:output_type -> health.SendNotificationResponse
	30, // 38: health.HealthService.AdminListRecommendations:output_type -> health.AdminListRecommendationsResponse
	32, // 39: health.HealthService.AdminUpsertRecommendation:output_type -> health.AdminUpsertRecommendationResponse
	34, // 40: health.HealthService.AdminDeleteRecommendation:output_type -> health.AdminDeleteRecommendationResponse
	36, // 41: health.HealthService.AdminUpsertCriterion:output_type -> health.AdminUpsertCriterionResponse
	27, // [27:42] is the sub-list for method output_type
	12, // [12:27] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_api_health_health_proto_init() }
func file_api_health_health_proto_init() {
	if File_api_health_health_proto != nil {
		return
	}
	file_api_health_health_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_health_health_proto_rawDesc), len(file_api_health_health_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_health_health_proto_goTypes,
		DependencyIndexes: file_api_health_health_proto_depIdxs,
		MessageInfos:      file_api_health_health_proto_msgTypes,
	}.Build()
	File_api_health_health_proto = out.File
	file_api_health_health_proto_goTypes = nil
	file_api_health_health_proto_depIdxs = nil
}
